### ISSUE TITLE
Allow user selection of ES modules to determine size after tree shaking

### ISSUE THREAD

**Issue by joeljeske** [pastelsky/bundlephobia#103]
## Type

Feature Request

First, I love bundlephobia and it is a great tool to see at a glance the cost of the next `yarn add ...`. I hope it brings awareness that not all packages are created equal :)

I would like to request a feature. It would be really cool if Bundlephobia could list the top level exports of a package when it encountered a package "that supports the module field". Then, it could allow me to choose which top-level exports I wanted to "use" and it could give me a more accurate size estimate for my use-case. 

Also, perhaps if it only had one top-level export we need not bother the user with the tree-shaking ability.

**Comment by pastelsky** [comment]
Hi! Do check out the `Exports Analysis` feature we launched for packages that export ES6 modules recently.

It gives you the size breakup of top-level exports. While you can't create a custom bundle, adding up sizes of the exports you use should be trivial.

Eg –
https://bundlephobia.com/result?p=rxjs@6.5.3
