### ISSUE TITLE
Does not work with animate.css

### ISSUE THREAD

**Issue by tan-nhu** [pastelsky/bundlephobia#11]
It seems npm-cost does not work with pure CSS module?

https://cost-of-modules.herokuapp.com/?p=animate.css

![screen shot 2017-09-01 at 10 02 24 am](https://user-images.githubusercontent.com/29714664/29980036-b2e75a64-8efc-11e7-84ea-668c1c4be933.png)

**Comment by pastelsky** [comment]
Thanks for reporting this issue. I've added beta support for CSS and SASS/SCSS packages. You can now see the sizes at - 
https://bundlephobia.com/result?p=animate.css@3.5.2
