### ISSUE TITLE
Composition is not showing.

### ISSUE THREAD

**Issue by adnaan1703** [pastelsky/bundlephobia#115]
## Bug
It has stopped showing the composition, it was super useful and used to show, now its not showing sometimes:

## intl-messageformat@2.2.0
This has one dependency on intl-messageParser and was super helpful before, this was one of the reason I use this platform. But somehow from last week it stopped showing composition.

### Entire error (stringified) I see in my browser console
NA

**Comment by pastelsky** [comment]
Thanks a lot for reporting this. Turns out, with the new recalibration we were doing for webpack 4, the key names in the API were changed. They should start to appear back again slowly (as cache wears out).

**Comment by adnaan1703** [comment]
Yeah this is resolved. Thanks a lot.
