### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by watadarkstar** [pastelsky/bundlephobia#118]
## Type
Failed to parse package [react-native-typing-animation](https://www.npmjs.com/package/react-native-typing-animation). 

The `package.json` of said package:

```
"devDependencies": {
    "prop-types": "^15.6.2",
    "react": "^16.6.3",
    "react-native": "^0.57.7",
    "release-it": "^8.2.0"
  },
  "peerDependencies": {
    "prop-types": "*",
    "react": "*",
    "react-native": "*"
  }
```

Not sure how to solve this without setting versions in peer dependencies or dependencies which I'd like to avoid.

## Package name
[react-native-typing-animation](https://www.npmjs.com/package/react-native-typing-animation)

### Entire error (stringified) I see in my browser console
```
"/tmp/tmp-build/packages/build-react-native-typing-animation@0.1.4-Ye5/node_modules/react-native-typing-animation/src/index.js 37:6
Module parse failed: Unexpected token (37:6)
You may need an appropriate loader to handle this file type.
| 
|     return (
>       <View style={[styles.container, style]}>
|         <Dot x={dotX - dotRadius - dotMargin} y={this.state.y1} radius={dotRadius} style={dotStyles} dotColor={dotColor} />
|         <Dot x={dotX} y={this.state.y2} radius={dotRadius} style={dotStyles} dotColor={dotColor} />
 @ /tmp/tmp-build/packages/build-react-native-typing-animation@0.1.4-Ye5/node_modules/react-native-typing-animation/index.js 1:0-52 1:0-52
 @ /tmp/tmp-build/packages/build-react-native-typing-animation@0.1.4-Ye5/index.js"
```

**Comment by pastelsky** [comment]
Bundlephobia does not support compilation of non-standard JS syntaxes (flow / typescript /jsx) as of today, and will probably not support it in the near future as well. This is because handling them means bundlephobia has to start using `babel-loader`, which is going to have a serious impact on compilation times.

**Comment by sibelius** [comment]
can we reopen this ?

having the same for https://bundlephobia.com/result?p=react-native-camera

**Comment by watadarkstar** [comment]
> If possible, we'd like to do it for react-native dependencies selectively, but I couldn't find a very good heuristic to determine if a package is meant to be used in react-native applications.

@pastelsky @sibelius Another simple solution to this problem would be to give the option to library maintainers to commit a `.bundlephobia` config file in the root of their repo. That file could specify what type of project it was, so bundlephobia can transpile accordingly. For example, a `.bundlephobia` could look like:

```JSON
{
    "projectType": "react-native"
}
```

**Comment by sibelius** [comment]
I think js-recoir can handle any type of project
