### ISSUE TITLE
[Feature Request] Ignore common libraries

### ISSUE THREAD

**Issue by theKashey** [pastelsky/bundlephobia#120]
## Type
Feature Request

### Feature Request
bundlephobia should not count common libraries like:
- tslib
- babel-helpers or @babel/runtime
- prop-types

Some libraries are quite small in reality, but these helpers, which would be shared among all the node_modules, hiding their true size.

It's still visible in package composition, but not quite quickly readable.

**Comment by wopian** [comment]
On the other hand, if it's the only package using those (vs. alternative packages or in your project) then it manipulates the true size of the package.

**Comment by theKashey** [comment]
On the other hand - this feature could encourage developers to actually stop inlining myriads of helpers, and make their bundlers smaller and faster (helpers would be _HOT_ optimized).
From my point of view it's the same feature as `ESM` exports or `sideEffects`, currently displayed on info pannel.

**Comment by pastelsky** [comment]
The packages you mention should then ideally be called out as peerDependencies. If they're direct dependencies, there is a good chance that their versions vary across different packages, and you're infact shipping with multiple copies of them.

Besides, maintaining such a list isn't going to be easy.

**Comment by pastelsky** [comment]
👍 Closing this then.
