### ISSUE TITLE
[Feature Request] show if es module is supported.

### ISSUE THREAD

**Issue by ashuanindian** [pastelsky/bundlephobia#122]
Since module support is now available in almost all major browsers, gradually it will be common practice to serve es modules to the latest browsers and legacy code to older browsers.

Showing if a library supports ES build will help in making the decision to include the library or not.

**Comment by pastelsky** [comment]
If you're talking about supporting ES6 exports, we already indicate that through the treeshaking flag. 

I don't think there are many libraries shipping with ES6 as source. Even if they did, I couldn't find a reliable way to detect that. There are talks of using the "source" field in pacakage.json to indicate untranspiled code, but this isn't a standard.

Open to suggestions on how we  could do this.

**Comment by ashuanindian** [comment]
Most of the libraries now shipping two builds. one which supports new es6 modules and another which supports UMD. Support of shipping es modules is currently available with rollup only and most libraries are using it to ship smaller bundles.

A quick search on https://www.pikapkg.com shows which all libraries support es modules. It using [pkg.modules](https://github.com/rollup/rollup/wiki/pkg.module) field from package.json.

If I search react than almost all related libraries are shipping es build except react(some of the work has been completed for this in this [PR ](https://github.com/facebook/react/pull/13080) 

It will be wonderful if bundlephobia can display separate gzip size of es build and umd build. Will help people to make the decision to ship es module build to supported browsers.

**Comment by pastelsky** [comment]
Let's continue the discussion https://github.com/pastelsky/bundlephobia/issues/391
Also I'm happy to accept PRs for this.
