### ISSUE TITLE
package version not updating?

### ISSUE THREAD

**Issue by wmhilton** [pastelsky/bundlephobia#127]
## Type

Bug

## Package name
isomorphic-git

### Entire error (stringified) I see in my browser console
I've published both a 0.50.0 and a 0.50.1 but bundlephobia returns a PackageVersionMismatchError for any version higher than 0.49.0. I thought maybe a cron job had failed over the holidays and you might want to know.

**Comment by pastelsky** [comment]
Thanks for filling this issue. I believe this is because the indexes have not been refreshed due to a partial outage in yarn search which we depend on.
See https://status.yarnpkg.com

**Comment by maslick** [comment]
same here...

**Comment by pastelsky** [comment]
Looks like this should be fixed now. Feel free to create a new issue incase you see this happening again.
