### ISSUE TITLE
sugest Grafoo over Apollo and Relay on similar packages 

### ISSUE THREAD

**Issue by malbernaz** [pastelsky/bundlephobia#128]
## Type
Feature Request

## Package name
Apollo and Relay

### Description
[Grafoo](https://github.com/grafoojs/grafoo) should be listed as an alternative to Relay and Apollo. It's way smaller, but has similar features.

**Comment by pastelsky** [comment]
Thanks for the suggestion. However, it does not seem like `Grafoo` meets the following criteria –

`Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.`

This does not mean `Grafoo` isn't a good library, but just that we plan to only offer well-known, maintained, and relevant libraries as suggestions in Bundlephobia.
