### ISSUE TITLE
Docs on methodology used by bundlephobia

### ISSUE THREAD

**Issue by nishanths** [pastelsky/bundlephobia#129]
## Type
Feature Request

## Package name
N/A

### Entire error (stringified) I see in my browser console
N/A

Is there human-readable documentation on the methodology that bundlephobia uses to determine a package's size?

**Comment by pastelsky** [comment]
I haven't written a doc, on it, but the core logic resides in this package - 
https://github.com/pastelsky/package-build-stats

**Comment by nishanths** [comment]
thanks, closing this!
