### ISSUE TITLE
Add kinka library as similar package for axios

### ISSUE THREAD

**Issue by js2me** [pastelsky/bundlephobia#132]

**Comment by pastelsky** [comment]
Thanks for the suggestion. However, it does not seem like `kinka ` meets the following criteria –

`Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.`

This does not mean `kinka` isn't a useful library, but just that we plan to only offer well-known, maintained, and relevant libraries as focussed suggestions in Bundlephobia.
