### ISSUE TITLE
react-scripts blacklisted

### ISSUE THREAD

**Issue by SamirJouni** [pastelsky/bundlephobia#136]
## Type

Bug

## Package name

react-scripts

### Entire error (stringified) I see in my browser console

fetching history triggered

Failed to load resource: the server responded with a status of 403 ()

{ 
code: "BlacklistedPackageError",
details: {},
message: "The package you were looking for is blacklisted due to suspicious activity in the past",
__proto__: Object
}

**Comment by pastelsky** [comment]
Yes, this is on purpose. See –
https://github.com/pastelsky/bundlephobia/issues/114#issuecomment-437242348
