### ISSUE TITLE
Similar Packages suggestion - "HTTP client libraries" request -> node-fetch

### ISSUE THREAD

**Issue by tolu** [pastelsky/bundlephobia#141]
## Type
when searching for `request`

## Package name
An alternative can be the package `node-fetch`

Category *HTTP client libraries*

**Comment by developit** [comment]
+ whatwg-fetch + unfetch.
These could also be shown for `axios`.

**Comment by pastelsky** [comment]
These will be available in the next release, thanks!
Note, I've split HTTP clients into browser-based (ky, whatwg-fetch) and node based (got, request).
