### ISSUE TITLE
API usage on npmtrends.com

### ISSUE THREAD

**Issue by johnmpotter** [pastelsky/bundlephobia#142]
Hey @pastelsky, 

I run a site ([npmtrends.com](https://www.npmtrends.com)) that lets you compare download counts for npm packages and i'd love to include the package size in the comparison. I've had a [few people request](https://github.com/johnmpotter/npm-trends/issues/21) this feature. 

It would look like the image below and the package size would link back to bundlephobia.com: 

<img width="1177" alt="screen shot 2019-02-20 at 3 52 10 pm" src="https://user-images.githubusercontent.com/5359194/53133371-c49b0080-3527-11e9-8b07-1ce0b449c708.png">

I'll include the header `'x-bundlephobia-user': 'npmtrends.com'` as mentioned in #72. 

I can set it up to handle any sort of rate limiting and i'll cache the results for each specific package version so it will only fetch from bundlephobia when the version updates.  

Please let me know if that is ok or if you have any questions.

Thanks a lot for your help and for running bundlephobia! 

John

**Comment by daKmoR** [comment]
hey,

just a thought but maybe displaying the badge is good enough? no need for extra api calls and no need to cache it yourself?

looks like this
<img src="https://badgen.net/bundlephobia/min/react" />

```html
<img src="https://badgen.net/bundlephobia/min/react" />
```

https://badgen.net/#bundlephobia

**Comment by johnmpotter** [comment]
@daKmoR Great idea, I went ahead and used the badge instead!
