### ISSUE TITLE
Trying to resolve "Missing peer dependencies error" for react-gpt

### ISSUE THREAD

**Issue by potench** [pastelsky/bundlephobia#15]
## Background
First, cool project, this has inspired us to add a travis hook to check the bundlesize of our projects and error if it exceeds a certain size: https://github.com/nfl/react-gpt/pull/47 

I was trying to see the distribution KB size footprint for react-gpt, and am seeing the "Missing peer dependencies error" here https://bundlephobia.com/result?p=react-gpt@0.2.5

I updated the peerDependencies in the project, bumped the version to 0.3.0, but still get the same error here https://bundlephobia.com/result?p=react-gpt@0.3.0

Is this a cache issue or have I not resolving the error correctly in the react-gpt project?

**Comment by pastelsky** [comment]
You made a typo :) 
Its spelt `peerDepencencies` here - 
https://unpkg.com/react-gpt/package.json

**Comment by potench** [comment]
:man_facepalming: thank you
