### ISSUE TITLE
MissingDependencyError

### ISSUE THREAD

**Issue by ManzDev** [pastelsky/bundlephobia#150]
## Type
Bug

## Package name
parcel-bundler

### Entire error (stringified) I see in my browser console
Try in website this package: parcel-bundler

Shows this message:

*MissingDependencyError*
This package (or this version) uses `./lib/Logger`, `./lib/WorkerFarm`, `./lib/errorUtils`, `./lib/fs` and `./lib/promisify`, but does not specify them either as a dependency or a peer dependency

*Stacktrace*
ModuleNotFoundError: Module not found: Error: Can't resolve './lib/Logger' in '/tmp/tmp-build/packages/build-parcel-bundler@1.12.3-UCJ/node_modules/@parcel/logger'

**Comment by pastelsky** [comment]
Bundlephobia is meant to be used for calculating sizes for libraries that might be shipped to clients. parcel-bundler is heavy and unlikely to be bundled in a client-side application. Moreover solving bundling errors for such tools can be tricky.

Solving for this is a low priority for us, however, you can use the [package-build-stats](https://github.com/pastelsky/package-build-stats) library and bundle it locally to get more details on why the bundling fails and submit a fix for the issue you see to either the library or to bundlephobia.
