### ISSUE TITLE
IntervalServerError 504 for @goodmind/flow-js

### ISSUE THREAD

**Issue by goodmind** [pastelsky/bundlephobia#151]
## Type

Bug

## Package name

@goodmind/flow-js

### Entire error (stringified) I see in my browser console

504 error
https://bundlephobia.com/api/size?package=@goodmind/flow-js&record=true
```
Failed to load resource: the server responded with a status of 504 ()
result.js:1 SyntaxError: Unexpected token < in JSON at position 0
```

**Comment by pastelsky** [comment]
This package seems to be too big for bundlephobia — its over 2.6 MB minified which is a lot!
Such packages are usually not meant to be bundled on the client-side, and it isn't a use case that Bundlephobia is suited to solve.
