### ISSUE TITLE
Cannot find existing packages

### ISSUE THREAD

**Issue by maxmalov** [pastelsky/bundlephobia#156]
## Type
Bug

## Package name
- `react-use`
- `react-router`
- `react-router-dom`

### Entire error (stringified) I see in my browser console

Searching all packages from above ends up with the same error

```
{"error":{"code":"PackageNotFoundError","message":"The package you were looking for doesn't exist.","details":{}}}
```

Also, these packages appear into autocomplete options list.

**Comment by maxmalov** [comment]
Hmm, looks like `react-router` & `react-router-dom` appear for now. But `react-use` still outputs `PackageNotFoundError`

**Comment by DominikSerafin** [comment]
also `recharts` `react-overlays` `react-redux` and a lot of others

**Comment by TylorS** [comment]
I'm also experiencing this as well with a package I published a few days ago. Is there a particular time interval in which it takes for packages to become available?

**Comment by pastelsky** [comment]
This should be fixed that now that we're using the official npm registry for resolving package versions. If you still notice this happening, feel free to open a new issue.
