### ISSUE TITLE
3Box is breaking bundlephobia

### ISSUE THREAD

**Issue by kuhnchris** [pastelsky/bundlephobia#158]
## Type
Bug

## Package name
3box (http://github.com/3box/3box-js)

### Entire error (stringified) I see in my browser console
![grafik](https://user-images.githubusercontent.com/761911/57087318-13230300-6d00-11e9-90a7-723c4e05d631.png)
SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"

**Comment by pastelsky** [comment]
This was probably happening due to the fact that 3Box is a humongous package. The recent versions seem to be building fine, so I'm closing this issue.
