### ISSUE TITLE
Wrong size for @parcel/watcher@2.0.0-alpha.3

### ISSUE THREAD

**Issue by astoilkov** [pastelsky/bundlephobia#159]
## Type
Bug

## Package name
@parcel/watcher

### Entire error (stringified) I see in my browser console
There isn't any error. It just reports the wrong size.

**Comment by pastelsky** [comment]
It reports the size of the bundled entry point –

https://unpkg.com/@parcel/watcher@2.0.0-alpha.5/index.js.

Note: `.node` bindings aren't compiled by webpack / bundlephobia. This package is probably meant to be used on server-side only, and the bundled size metric isn't very meaningful for it anyways.

**Comment by astoilkov** [comment]
It can be used in Electron where it is meaningful to know the size.
