### ISSUE TITLE
Bars out of order

### ISSUE THREAD

**Issue by DominikSerafin** [pastelsky/bundlephobia#16]
When I was testing my own package ([Vuebar](https://github.com/DominikSerafin/vuebar)) I've got a little confused because it seems that the bars were out of order. 

This image should show it very clearly:

![https://bundlephobia.com/result?p=vuebar@0.0.17](https://i.imgur.com/7sFYppf.png)

BTW. This project is awesome 😄

**Comment by pastelsky** [comment]
This was happening since the versions were being treated as strings. Should be fixed now.
And thanks :)
