### ISSUE TITLE
Similar packages suggestion - element-motion

### ISSUE THREAD

**Issue by madou** [pastelsky/bundlephobia#165]
## Type
Similar package suggestion

## Package name
`@element-motion/core`

Similar to gsap, mo-js, popmotion, react-flip-toolkit, pose, react-flip-move, react-spring, react-motion

**Comment by pastelsky** [comment]
Thanks for the suggestion. However, it does not seem like @element-motion/core
meets the following criteria –

`Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.`

Of course, this does not mean @element-motion/core isn't a useful library, but just that we plan to only offer well-known, maintained, and relevant libraries as focussed suggestions in Bundlephobia.
