### ISSUE TITLE
MissingDependencyError: react_ujs

### ISSUE THREAD

**Issue by 0xdevalias** [pastelsky/bundlephobia#166]
## Type
Bug

## Package name

https://www.npmjs.com/package/react_ujs
https://github.com/reactjs/react-rails/tree/master/react_ujs

### Entire error (stringified) I see in my browser console
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'react' in '/tmp/tmp-build/packages/build-react_ujs@2.5.0-qoJ/node_modules/react_ujs/react_ujs'
```

**Comment by pastelsky** [comment]
Please read this –
https://github.com/pastelsky/bundlephobia#1-why-does-search-for-package-x-throw-missingdependencyerror-
