### ISSUE TITLE
Page doesn't reload when clicking on package link before prev request completes

### ISSUE THREAD

**Issue by donysukardi** [pastelsky/bundlephobia#17]
**Steps to Reproduce**
* Search for any package
* Before RESOLVING VERSION AND DEPENDENCIES completes, scroll down and click on any package under Recent Searches
* URL query param gets updated, but the page doesn't reload with the new package

![bundlephobia-issue](https://user-images.githubusercontent.com/410792/30633250-8b4fd582-9e1d-11e7-8b84-972aa38e6bb2.gif)

**Comment by pastelsky** [comment]
This is a known issue. PR's welcome :)

**Comment by pastelsky** [comment]
This is fixed now.
