### ISSUE TITLE
Build Error for Next React Framework

### ISSUE THREAD

**Issue by maxwaiyaki** [pastelsky/bundlephobia#170]
## Type

Bug
## Package name
Next JS React Framework

### Entire error (stringified) I see in my browser console
BuildError
Failed to build this package.

**Comment by pastelsky** [comment]
Bundlephobia is meant to be used for calculating sizes for libraries that might be shipped to clients. Next JS is heavy and unlikely to be bundled in a client-side application. 

Solving for this is a low priority for us, however, you can use the [package-build-stats](https://github.com/pastelsky/package-build-stats) library to try and bundle it locally and submit a fix for the issue you see to either the library or to bundlephobia.
