### ISSUE TITLE
Browser back button doesn't work

### ISSUE THREAD

**Issue by Daniel15** [pastelsky/bundlephobia#171]
## Type
Bug

## Package name
urql

Go to https://bundlephobia.com/result?p=urql@1.0.5
Click 1.0.4 in the graph
Page correctly updates, and URL changes to `?p=urql@1.0.4`
Click the browser's back button
Notice that the URL changes back to 1.0.5, but the page is actually still displaying 1.0.4.

**Comment by pastelsky** [comment]
Thanks for reporting this @Daniel15. I'm marking this as a good first issue for contributors.

**Comment by devshun** [comment]
@pastelsky 

I've created a pull request to resolve this issue. Please review it!

https://github.com/pastelsky/bundlephobia/pull/782
