### ISSUE TITLE
EntryPointError raised but package exists.

### ISSUE THREAD

**Issue by fabiocaccamo** [pastelsky/bundlephobia#185]
**Describe the bug**
I tried to test my npm packages, but I receive an *EntryPointError*, here a list of some packages of mine that you could use for debug this issue:
-   `@fabiocaccamo/utils.js`
-   `@fabiocaccamo/layers.css`
-   `@fabiocaccamo/wall.css`

*(I think that the cause of this issue is the @fabiocaccamo prefix)*

**To Reproduce**
Just search `@fabiocaccamo/utils.js`

**Expected behavior**
Show result page without errors.

**Comment by pastelsky** [comment]
Hi Fabio, 
I believe the errors are correct? I don’t see the entry points (specified in the `main` field) in the packages you’ve listed –

https://unpkg.com/@fabiocaccamo/utils.js@0.9.10
https://unpkg.com/@fabiocaccamo/layers.css@0.1.4
https://unpkg.com/@fabiocaccamo/wall.css@0.0.3

**Comment by pastelsky** [comment]
Closing this as this does not seem like an issue – the error is valid. Feel free to open another issue in-case you feel otherwise.
