### ISSUE TITLE
PackageVersionMismatchError

### ISSUE THREAD

**Issue by bvego** [pastelsky/bundlephobia#186]
**Describe the bug**
I've released a new version of my package 2 days ago but BundlePhobia can't find the new version. It's currently stuck at 0.6.0 even though 2 more versions were released.

Npm link: https://www.npmjs.com/package/nope-validator
GitHub link: https://github.com/bvego/nope-validator

**To Reproduce**
https://bundlephobia.com/result?p=nope-validator

Overriding with: https://bundlephobia.com/result?p=nope-validator@0.7.2 shows a `PackageVersionMismatchError` that reports that it is still stuck on 0.6.0

**Expected behavior**
It should report the newest package version details (0.7.2) and be able to find it. Maybe I missed something - but NPM shows 0.7.2 and I've correctly tagged it as such in GitHub

Awesome project by the way!

**Comment by bvego** [comment]
Seems it picked it up now 😅 

Closing this

**Comment by bvego** [comment]
But something else happened:
https://monosnap.com/file/quAvN0l1ky3koCw9JDlEuCO3C6Zk2O

When the package is queried or accessed through this link 
https://bundlephobia.com/result?p=nope-validator
it navigates to 0.6.0 even though it registers the version 0.7.3

**Comment by bvego** [comment]
Update:

https://monosnap.com/file/NYqIUp61rw3OPDFaitgTk5lPgyU4vI

Now searching for it displays the correct last version but it is missing the history - every version before 0.7.1

**Comment by jennifer-shehane** [comment]
I'm having the same issue. Our package has a newer released version that isn't showing up as registered in bundlephobia. Wondering how frequently the data is fetched for this? Why wouldn't a newly published version be found? It's version is shown as published on npm.

**Comment by pastelsky** [comment]
This was occurring because of the algolia index we used to resolve package versions – it often lagged official npm registry data. This is should be fixed in the next release (by tomorrow) now that we've switched to using the official registry.
