### ISSUE TITLE
Failed to parse knex

### ISSUE THREAD

**Issue by mceachen** [pastelsky/bundlephobia#187]
This is a great service! Great idea, clean UX! :100: 

**Describe the bug**

## MissingDependencyError
This package (or this version) uses `mssql/lib/base` and `mssql/package.json`, but does not specify them either as a dependency or a peer dependency

**To Reproduce**

https://bundlephobia.com/result?p=knex

**Expected behavior**

No errors.

**Comment by pastelsky** [comment]
Thanks a lot for your kind words. This seems to be working fine now, closing this issue. Feel free to open a new one in case you feel this is still an issue.
