### ISSUE TITLE
statty

### ISSUE THREAD

**Issue by vesparny** [pastelsky/bundlephobia#19]
Not sure why I am not able to get the bundle size for

https://www.npmjs.com/package/statty

![image](https://user-images.githubusercontent.com/82070/30816309-f0f1f9b4-a215-11e7-9d47-80649d21096d.png)

**Comment by davidchase** [comment]
looks like it works now https://bundlephobia.com/result?p=statty@1.0.0

![image](https://user-images.githubusercontent.com/490291/30976697-72da12f2-a443-11e7-9a00-4d2358309cfd.png)

**Comment by pastelsky** [comment]
Cool. Let me know if you face similar issues again!
