### ISSUE TITLE
Similar package suggestion - cb-fetch

### ISSUE THREAD

**Issue by Mouvedia** [pastelsky/bundlephobia#190]
## Package Type
HTTP client libraries

## Package URL
https://github.com/Mouvedia/cb-fetch

**Comment by pastelsky** [comment]
We don't want to maintain an exhaustive list of packages for each category – that isn't very scalable. We aim to keep only the top 4-5 in each and hence the quality checks are essential for us to be able to offer packages as a suggestion.

Quality Checks –

 - Package has sufficient overlap in functionality to act as a replacement.
 - Package is actively maintained, and/or stable for use.
 - Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

Thanks for the suggestion!

**Comment by Mouvedia** [comment]
@pastelsky could you add these requirements to the README?

**Comment by pastelsky** [comment]
@Mouvedia These are a part of the new Issue template – this probably didn't exist back in 2018. Apologies for that.
