### ISSUE TITLE
Crush with 502 by direct link

### ISSUE THREAD

**Issue by Akiyamka** [pastelsky/bundlephobia#191]
**Describe the bug**
If you open direct link https://bundlephobia.com/result?p=effector@20.0.0 or just refresh page after search - page crush with 502 Error

**Comment by simonurmi** [comment]
Not sure if related, but searching for packages like  `@sindresorhus/is` or `@babel/core` results in 502.

**Comment by dcastil** [comment]
I also get a 502 when I search for any package.

**Comment by kevin-kraus** [comment]
Seems like the whole website is experiencing issues right now. 

Same Problem here searching for some packages may work but for others "An unexpected Error occurred". 

Scanning a package.json is fully impossible -> instantly errors and on reload CloudFlares "Bad Gateway" page appears.

**Comment by pastelsky** [comment]
Ah, yes. The site did go down for a bit longer than it should’ve (auto-restart seems to have failed). Should be back up now. Sorry for that!
