### ISSUE TITLE
Add immerjs to similar package

### ISSUE THREAD

**Issue by alexbaumgertner** [pastelsky/bundlephobia#193]
## Type
Feature Request

## Package name
Could you please add https://github.com/immerjs/immer Similar Packages for [immutable](https://bundlephobia.com/result?p=immutable@4.0.0-rc.12)

**Comment by pastelsky** [comment]
I don't believe `immer` (a state management library based on immutable data structures) is a replacement for `immutable` (implementation of immutable data structures). We'd want the alternatives to be replaceable.

Thanks for the suggestion!
