### ISSUE TITLE
<error-name>: <package-name> fails to <condition>

### ISSUE THREAD

**Issue by peterbe** [pastelsky/bundlephobia#196]
## Package name
I uploaded a `package.json` from disk. It was this file: https://github.com/peterbe/django-peterbecom/blob/34c712ff2dbcf56256368184545a04df3afa4449/songsearch-autocomplete-preact/package.json

### Entire (stringified) error that I see in my browser console

Does the screenshot help?

<img width="1238" alt="Screen Shot 2019-07-17 at 10 33 17 AM" src="https://user-images.githubusercontent.com/26739/61384534-c66eb300-a87e-11e9-9923-df8bfe1eb9a6.png">

**Comment by pastelsky** [comment]
This `pacakge.json` seems to work fine now. So I'm assuming whatever issue you faced has been fixed. Thanks for the bug report, and apologies for the late response.
