### ISSUE TITLE
momentjs alternative

### ISSUE THREAD

**Issue by CupCakeArmy** [pastelsky/bundlephobia#197]
## Type
Feature request

## Package name
similar package for momentjs.

I wrote a little library that emulates the duration component of Momentjs as a addition to dayjs, which only handles time
https://github.com/cupcakearmy/uhrwerk

**Comment by pastelsky** [comment]
Thanks for the suggestion. However, it does not seem like `uhrwerk` meets the following criteria –

Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

This does not mean `uhrwerk` isn't a useful library, but just that we plan to offer well-known, maintained, and relevant libraries as focussed suggestions in Bundlephobia.
