### ISSUE TITLE
Package suggestion: @sifrr/fetch for axios

### ISSUE THREAD

**Issue by aaditya-taparia** [pastelsky/bundlephobia#198]
**Package name**
@sifrr/fetch

**Alternative to**
axios

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [ ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
Thanks for the suggestion. However, it does not seem like cashify meets the following criteria –

Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

This does not mean @sifrr/fetch isn't a good library, but just that we plan to only offer well-known, mantained, and relevant libraries as suggestions in Bundlephobia.
