### ISSUE TITLE
Package suggestion: react-spring for react-motion

### ISSUE THREAD

**Issue by Kevin-Hamilton** [pastelsky/bundlephobia#199]
**Package name**
react-spring

**Alternative to**
Similar to gsap, mo-js, popmotion, pose, react-motion

**Quality check**

- [ X ] Package has sufficient overlap in functionality to act as a replacement.
- [ X ] Package is actively maintained, and/or stable for use.
- [ X ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category** 
general-purpose-animation

**Comment by pastelsky** [comment]
Already included under the "react based animation libs" category now. Closing this.
