### ISSUE TITLE
Package suggestion: <alternative>immutability-helper<package / category>

### ISSUE THREAD

**Issue by Domino987** [pastelsky/bundlephobia#200]
**immutability-helper**

**Alternative to**
immer

**Quality check**

- [ ] Package has sufficient overlap in functionality to act as a replacement.
- [ ] Package is actively maintained, and/or stable for use.
- [ ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
Immutability
https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
Thanks for the suggestion! `immutability-helper` will be added to the list in the next release 🎉
