### ISSUE TITLE
Package suggestion: linaria for CSS in JS libraries

### ISSUE THREAD

**Issue by andreev-danila** [pastelsky/bundlephobia#203]
**Package name**
linaria
**Alternative to**
styled-components, radium, emotion, glamor 

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
CSS in JS libraries

**Comment by pastelsky** [comment]
Thanks for the suggestion! `linaria` will be added to the list in the next release 🎉
