### ISSUE TITLE
Package suggestion: '@hookstate/core' for 'State Management Libraries (React only)'

### ISSUE THREAD

**Issue by avkonst** [pastelsky/bundlephobia#206]
Raising for you to consider. You may cancel it if it does not satisfy your criteria.

**Package name**
@hookstate/core
https://github.com/avkonst/hookstate
https://www.npmjs.com/package/@hookstate/core

**Alternative to**
mobx-react-lite, react-redux, react-formik

**Quality check**

- Yes - Package has sufficient overlap in functionality to act as a replacement.
- Yes - Package is actively maintained, and/or stable for use.
- No - Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
State Management Libraries (React only) - new sub category with more generic State Management Libraries

**Comment by pastelsky** [comment]
Hi @avkonst. Thanks a lot for opening a suggestion.

State management is quite a saturated category as you'd expect, and the Quality checks go a long way towards ensuring we're offering the best suggestions to our users. This might sometimes mean that we're conservative in adding newer packages as suggestions, and us limiting suggestions to a maximum of only 4-5 per category.

The package suggested by you is probably helpful but does not fit the criteria I've outlined above. In the interest of keeping our suggestions focused, I'm afraid we cannot add this suggestion to state management at the moment.
