### ISSUE TITLE
Package suggestion: Reactochart for Victory/React-Vis/eCharts

### ISSUE THREAD

**Issue by krissalvador27** [pastelsky/bundlephobia#207]
**Package name**
Reactochart
https://github.com/spotify/reactochart

**Alternative to**

Victory

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [ ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Comment by pastelsky** [comment]
Thanks for the suggestion. We wouldn't be able to accept this as this does not meet all of the three criteria, and the category is already crowded.
