### ISSUE TITLE
dompurify@1.1.1 cannot be built

### ISSUE THREAD

**Issue by johnrackles** [pastelsky/bundlephobia#208]
## Type
latest version of dompurify package cannot be built. The error details are empty when I look at the console.

## Package name
dompurify@1.1.1

### Entire error (stringified) I see in my browser console
​
code: "InstallError"
​​
details: Object {  }
​​
message: "Installing the packaged failed."

**Comment by pastelsky** [comment]
`1.1.1` is not a valid version for `dompurify`. Please see —
https://www.npmjs.com/package/dompurify
