### ISSUE TITLE
500 Error on submitting 'Elm'

### ISSUE THREAD

**Issue by sleepyfox** [pastelsky/bundlephobia#21]
When trying to calculate the size of 'Elm', app hangs at 'calculating files sizes'. Chrome dev tools shows the below in the console:

```
app.js:7 GET https://bundlephobia.com/api/size?package=elm&record=true 500 ()
result:3 Uncaught (in promise) TypeError: Cannot read property 'code' of undefined
    at t.value (result:3)
    at p._renderValidatedComponentWithoutOwnerOrContext (app.js:26)
    at p._renderValidatedComponent (app.js:26)
    at p._updateRenderedComponent (app.js:26)
    at p._performComponentUpdate (app.js:26)
    at p.updateComponent (app.js:26)
    at performUpdateIfNecessary (app.js:26)
    at Object.performUpdateIfNecessary (app.js:7)
    at s (app.js:7)
    at r.perform (app.js:7)
```

**Comment by pastelsky** [comment]
The package you're referring to is a npm wrapper over platform binaries primarily written in languages other than JS. Building this is out of scope for this project.

**Comment by sleepyfox** [comment]
Maybe remove it from the list then?

**Comment by pastelsky** [comment]
Which list are you referring to?

**Comment by sleepyfox** [comment]
I was referring to the list of packages, but I assume you're just
deferring that search to npm. It would be nice to at least catch the
packages that stall in 'checking files sizes' due to native
dependencies and putting up a user-friendly error message along the
lines of "Cannot calculate file size due to native code dependencies"
or something similar.

**Comment by pastelsky** [comment]
There isn't currently a general way to detect that I'm afraid.

**Comment by OmgImAlexis** [comment]
@pastelsky I'm guessing this means any builtins like path, url, etc?

Getting the same error with [`medusa-lib`](https://bundlephobia.com/api/size?package=medusa-lib&record=true).

**Comment by pastelsky** [comment]
@OmgImAlexis The error in medusa-lib is due to it using `es2017` features (spread operators) in it's entry point. We support only limited transpilation of npm packages (only features supported by `uglify-es`) and either way, it's a best practice to transpile your code before publishing it to npm.

Please feel free to open a new issue if you've any queries about this.
