### ISSUE TITLE
Package suggestion: cashify for money

### ISSUE THREAD

**Issue by xxczaki** [pastelsky/bundlephobia#211]
**Cashify**

**Alternative to**
- [money.js](https://github.com/openexchangerates/money.js/)

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
Currency conversion

---

Note: `Number and Currency Formatting` category does not fit this package.

**Comment by pastelsky** [comment]
Thanks for the suggestion @xxczaki. However, it does not seem like `cashify` meets the following criteria –

`Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.`

This does not mean cashify isn't a good library, but just that we plan to only offer well-known, mantained, and relevant libraries as suggestions in Bundlephobia.
