### ISSUE TITLE
Incorrect size comparison for differences over 100% 

### ISSUE THREAD

**Issue by ViLPy** [pastelsky/bundlephobia#212]
**Describe the bug**
When size difference between two packages more than 100%, difference is shown as incorrect multiplier

**To Reproduce**
https://bundlephobia.com/result?p=recharts@1.7.1 (120.5kB min + gzip) comparison with `echarts` (258.5kB min + gzip) shows `1.15x larger`. However 120.5 * 1.15 is only 138.57 and not 258.5

**Expected behavior**
This is true for percentage (it is 115% bigger), but multiplier should be `2.15x larger` then

**Comment by pastelsky** [comment]
Yeah, that's true. Probably got overlooked. Would you be willing to send out a PR with a fix? 
I use human readable css class names, so locating the source should be easy.

**Comment by ViLPy** [comment]
Done! Please review
