### ISSUE TITLE
404: universal-github-app-jwt fails to return size on /api/packages/size?package=universal-github-app-jwt@1.0.1

### ISSUE THREAD

**Issue by gr2m** [pastelsky/bundlephobia#214]
## Package name

[universal-github-app-jwt](https://bundlephobia.com/result?p=universal-github-app-jwt@1.0.1)

### Entire (stringified) error that I see in my browser console

Just a 

> 404 | This page could not be found.

Size is shown on https://bundlephobia.com/result?p=universal-github-app-jwt@1.0.1, but the API call returns a 404: https://bundlephobia.com/api/packages/size?package=universal-github-app-jwt@1.0.1

**Comment by pastelsky** [comment]
The API is https://bundlephobia.com/api/size?package=universal-github-app-jwt@1.0.1
I think you were hitting the wrong path.
