### ISSUE TITLE
Package suggestion: showdown for markdown

### ISSUE THREAD

**Issue by rakeshta** [pastelsky/bundlephobia#215]
**Package name**
`showdown`

**Alternative to**
`marked` and other markdown parsons.

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
markdown-parser (Markdown Parser)

**Comment by pastelsky** [comment]
Thanks for the suggestion. This will be added in the next release of bundlephobia 🎉
