### ISSUE TITLE
Package suggestion: react-hook-form for redux-form (Category - React based form builders)

### ISSUE THREAD

**Issue by rockeynebhwani** [pastelsky/bundlephobia#217]
**Package name**
react-hook-form (see http://react-hook-form.com)

**Alternative to**
redux-form

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
React based form builders

**Comment by pastelsky** [comment]
Thanks for the suggestion! This will replace the suggestion for `redux-form` in the next release.

**Comment by bluebill1049** [comment]
This is amazing news for react-hook-form 🙏 thank you guys
