### ISSUE TITLE
Exports Analysis returns a BuildError Failed to build this package

### ISSUE THREAD

**Issue by tleunen** [pastelsky/bundlephobia#219]
**Describe the bug**

I've tried to see the exports analysis for the `@shopify/polaris` package and it returns a build error.
```
BuildError
Failed to build this package.

[object Object]
```

```
{
   "error":{
      "code":"BuildError",
      "message":"Failed to build this package.",
      "details":{
         "name":"BuildError",
         "originalError":{
            "operation":"PACKAGE_EXPORTS_SIZES",
            "reason":"BUILD_SERVICE_UNREACHABLE",
            "url":"http://localhost:7002/exports-sizes?p=%40shopify%2Fpolaris%404.2.1"
         }
      }
   }
}
```

**To Reproduce**
Access https://bundlephobia.com/result?p=@shopify/polaris@4.2.1

**Expected behavior**
Show the exports analysis.

**Comment by pastelsky** [comment]
`BUILD_SERVICE_UNREACHABLE` usually implies a downtime with our build worker nodes. This might have happened due to rise in traffic / another temporary issue.

I see that the recent versions of polaris report sizes just fine.
