### ISSUE TITLE
Package suggestion: react-pose-text for animation libraries

### ISSUE THREAD

**Issue by FMakareev** [pastelsky/bundlephobia#220]
**Package name**
react-pose-text
https://github.com/Popmotion/popmotion/tree/master/packages/react-pose-text

**Alternative to**
react-text-transition

**Quality check**

- [Yes] Package has sufficient overlap in functionality to act as a replacement.
- [Yes] Package is actively maintained, and/or stable for use.
- [Yes] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
general-purpose-animation

**Comment by pastelsky** [comment]
Thanks for the suggestion @FMakareev. Text animation is too small a niche that does not fit the `general-purpose-animation` category. Moreover, they are react-specific. 
Closing this for now, but if you feel this can become a new category on its own  and occupies sufficient mind space, feel free to @ me.
