### ISSUE TITLE
Package suggestion: exceljs for xlsx

### ISSUE THREAD

**Issue by kahatie** [pastelsky/bundlephobia#221]
**Package name**
exceljs
**Alternative to**
xlsx

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [ ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
Will be added to the next release, thanks!
