### ISSUE TITLE
Package suggestion: react-apollo for urql

### ISSUE THREAD

**Issue by ryan-gilb** [pastelsky/bundlephobia#227]
**Package name**

[react-apollo](https://github.com/apollographql/react-apollo)

**Alternative to**

[urql](https://github.com/FormidableLabs/urql)

**Quality check**

✅Package has sufficient overlap in functionality to act as a replacement.
✅Package is actively maintained, and/or stable for use.
✅Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
GraphQL Clients

**Comment by pastelsky** [comment]
`@apollo/client` would be added shortly. Thanks for your suggestion.
