### ISSUE TITLE
Package suggestion: `redux-form` for `react-final-form`

### ISSUE THREAD

**Issue by showmeyourhits** [pastelsky/bundlephobia#230]
**Package**
`redux-form`

**Alternative to**
`react-final-form`

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
react-form

`react-final-form` even has guide for migration from `redux-form`
https://final-form.org/docs/react-final-form/migration/redux-form

**Comment by pastelsky** [comment]
`react-final-form` is a part of suggestions, and `redux-form` has a deprecation-like warning on its front page. Closing this. Thanks for your suggestions.
