### ISSUE TITLE
Package suggestion: pyro-form for formik (Category - React based form builders)

### ISSUE THREAD

**Issue by treylon** [pastelsky/bundlephobia#236]
**Package name**

Pyro-Form - https://github.com/eversport/pyro-form

**Alternative to**

formik - https://bundlephobia.com/result?p=formik

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [ ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**

React based form builders & validators

**Comment by pastelsky** [comment]
Thanks for your suggestion. We wouldn't be able to accept it at this point of time because it does not meet the three criteria listed and the category is already crowded.
