### ISSUE TITLE
Package suggestion: effector for alternative of mobx

### ISSUE THREAD

**Issue by sergeysova** [pastelsky/bundlephobia#237]
**Package name**
effector

**Alternative to**
mobx

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.
- [x] Package is actively maintained, and/or stable for use.

**Category**
state-management

**Comment by pastelsky** [comment]
Thanks for your suggestion. State management is a crowded category and we wish to keep suggestions limited to 4-5 for them to remain effective. We wouldn't be able to incorporate this at the moment.
