### ISSUE TITLE
Proposal to add `npm install size`

### ISSUE THREAD

**Issue by antonk52** [pastelsky/bundlephobia#238]
Not all packages are used on the front end where it is a good practice to minify and compress the code before sending it to the browser. When used only on the server side minified and gzip numbers do not matter as much. However plain size of a package matters to figure out why npm install's are taking so long.

I would like to propose adding another category of `plain package size`. In other words how much data you need to install the package with its dependencies.

**Comment by southpolesteve** [comment]
You should check out Packagephobia https://packagephobia.now.sh/

**Comment by antonk52** [comment]
My bad. This looks great. Perhaps both resources can link to one another. Thank you!

I guess this issue can be closed
