### ISSUE TITLE
500 when fetching info for semantic-ui

### ISSUE THREAD

**Issue by chrisgbaker** [pastelsky/bundlephobia#24]
https://bundlephobia.com/result?p=semantic-ui
Not that important for my needs, as I was more curious about `semantic-react`, but I figured I'd make you aware something is going on here. Anytime I try and check the size for this package, a 500 is returned.

**Comment by matchu** [comment]
I'm seeing a similar error for `create-react-class`. https://bundlephobia.com/result?p=create-react-class

**Comment by pastelsky** [comment]
@matchu `create-react-class` seems to be working. 
@chrisgbaker bundlephobia is hosted on heroku, which has a hard limit of 30s to process incoming requests. Since `semantic-ui` is a pretty large package and building / minifying / gzipping it takes a lot of time, we error out.
I've corrected the error message in this case to be more descriptive.

**Comment by Saturate** [comment]
I get his for most packages, I tried `make-fetch-happen` and could not get that.

Seems like we could keep it alive by sending back a status on the build: https://devcenter.heroku.com/articles/limits#http-timeouts

Would this be possible?

**Comment by n1ru4l** [comment]
This is also the case for https://github.com/n1ru4l/graphql-schema-generator-rest (https://bundlephobia.com/result?p=@n1ru4l/graphql-schema-generator-rest)

 I thought this was related to the scoped package name. However it is working fine with `@babel/polyfill`.

**Comment by pastelsky** [comment]
@n1ru4l The underlying error is this - 
`You seem to be using `graphql` as a dependency in code, but have not listed it either as a peerDependency or a direct dependency in package.json`

**Comment by styfle** [comment]
I'm not sure if this is the same bug but I am unable to see the size of `immer`

https://bundlephobia.com/result?p=immer@0.7.0

**Comment by Raiondesu** [comment]
@styfle, no, this time it's different.
See #43

**Comment by n1ru4l** [comment]
@pastelsky So this means that if I add a package that has a peerDependency I also have to add it as a peerDependency or dependency?

**Comment by chrisinajar** [comment]
Probably a different error but this seems to be where people are pasting packages that cause various 500 errors

https://bundlephobia.com/result?p=@commaai/pandajs
UI hangs forever, server sends a 500. If I had to guess, it's failing to install the `usb` dependency.

**Comment by Raiondesu** [comment]
+1, @chrisinajar, also experiencing this.

**Comment by pastelsky** [comment]
Closing this since all of the packages mentioned seem to be working fine now.
