### ISSUE TITLE
Package suggestion: @hapi/joi for yup

### ISSUE THREAD

**Issue by jonager** [pastelsky/bundlephobia#243]
**Package name**

**Alternative to**

**Quality check**

- [ ] Package has sufficient overlap in functionality to act as a replacement.
- [ ] Package is actively maintained, and/or stable for use.
- [ ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
Thanks for your suggestion. We wouldn't be able to accept it at this point of time because it does not meet the three criteria listed and the category is already crowded.
