### ISSUE TITLE
Package suggestion: Ez-Validation for form/ schema based validation

### ISSUE THREAD

**Issue by Amad27** [pastelsky/bundlephobia#249]
**Package name**
Ez-Validation
**Alternative to**
yup

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
schema based validation, and form validation.

**Comment by pastelsky** [comment]
Thanks for the suggestion @Amad27 , it looks like a neat library. Schema validation is a very crowded category already, and we do not exhaustively want to list all such libraries here at the moment. I believe the ones that we list today are more widely used, so we're not inclined to extend our recommendations as of now.
