### ISSUE TITLE
Package suggestion: react-spring for framer-motion / react animation

### ISSUE THREAD

**Issue by emadabdulrahim** [pastelsky/bundlephobia#251]
**Package name**
`framer-motion`

**Alternative to**

`react-spring`
https://github.com/react-spring/react-spring

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
react animation
<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
Thanks for the suggestions!
