### ISSUE TITLE
Package suggestion: <alternative> for <package / category>

### ISSUE THREAD

**Issue by shirish-heller** [pastelsky/bundlephobia#252]
**Package name**
workflow-record-and walkthrough
**Alternative to**

driver.js, shepherd.js, intro.js
**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
Thanks for the suggestion @shirish-heller, but this package seems to lack good documentation on usage and does not seem to have many users (contrary to the checkmark you've added). We want to keep our suggestion focussed at the moment, and would not be able to add this to our suggestions.
