### ISSUE TITLE
Package suggestion: trumbowyg for <tinymce / rich-text-editors>

### ISSUE THREAD

**Issue by efrenpastor** [pastelsky/bundlephobia#254]
**Package name**
trumbowyg

**Alternative to**
tinymce / rich-text-editors

**Quality check**

- [✓] Package has sufficient overlap in functionality to act as a replacement.
- [✓] Package is actively maintained, and/or stable for use.
- [✓] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
rich-text-editors

**Comment by pastelsky** [comment]
Thanks for the suggestion @efrenpastor, it looks like a neat library. Text-editors is a very crowded category, and we do not exhaustively want to list all editor libraries here at the moment. I believe the ones that we list today are more widely used and don't need jQuery as a dependency, so we're not inclined to extend our recommendations as of now.
