### ISSUE TITLE
Package suggestion: messageformat for intl-messageformat

### ISSUE THREAD

**Issue by xeophin** [pastelsky/bundlephobia#255]
**Package name**
[messageformat](https://www.npmjs.com/package/messageformat)

**Alternative to**
- intl-messageformat

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
- Natural language date-time utilities
- Localisation
- Internationalisation

**Comment by pastelsky** [comment]
Thanks for the suggestion @xeophin. I don't believe the categories suggested for this library describe it well, and I'm not sure if creating a new category for this would be fair. It seems to perform a rather specific functionality when it comes to i18n and isn't a generic i18n library.

**Comment by xeophin** [comment]
As far as I remember I based these category suggestions on other similar packages – and I remember that I wasn't exactly happy with the "natural language date-time utilities", but this was the category that had been applied to other, functionally similar packages. 

Functionalitywise, `messageformat` is most similar to `intl-messageformat`, so I guess those two should just be in the same category, whichever one you find appropriate.

**Comment by pastelsky** [comment]
> As far as I remember I based these category suggestions on other similar packages – and I remember that I wasn't exactly happy with the "natural language date-time utilities", but this was the category that had been applied to other, functionally similar packages.

If you thought the suggestion was inaccurate, could you raise an issue with an example? We should be able to tweak matches so that they are more meaningful.

As for `messageformat`, I've created a new category and this would be added to the next release.
