### ISSUE TITLE
Package suggestion: apexcharts for chart.js

### ISSUE THREAD

**Issue by junedchhipa** [pastelsky/bundlephobia#256]
**Package name**
[apexcharts](https://github.com/apexcharts/apexcharts.js)

**Alternative to**
[chart.js](https://github.com/chartjs/Chart.js)

**Quality check**
- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
 Charting libraries

**Comment by pastelsky** [comment]
Thanks for the suggestion @junedchhipa, but charting is a very crowded category, and we do not exhaustively want to list all charting libraries here at the moment. I believe the ones that we list today are more widely used.
