### ISSUE TITLE
Build error with no clear cause.

### ISSUE THREAD

**Issue by Westbrook** [pastelsky/bundlephobia#257]
## Type
Error spelunking.

## Package name
@spectrum-web-components/icons

### Entire error (stringified) I see in my browser console
{"code":"BuildError","message":"Failed to build this package.","details":{"name":"BuildError"}}"

If there's an issues I've not encountered in other build contexts with my package, I'd love to be able to correct it. Please let me know what you find!

**Comment by pastelsky** [comment]
There was an issue with a loose regex in the webpack config. This has been fixed and should be released with the next update of `package-build-stats`. Thanks for taking time to report the issue.
