### ISSUE TITLE
Package suggestion: eo-locale for react-intl

### ISSUE THREAD

**Issue by pret-a-porter** [pastelsky/bundlephobia#258]
**Package name**
[eo-locale](https://github.com/ibitcy/eo-locale)

**Alternative to**
[react-intl](https://github.com/formatjs/react-intl)

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [ ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
Number and Currency Formatting.

**Comment by pastelsky** [comment]
Thanks for the suggestion.
