### ISSUE TITLE
Heroku: Application Error

### ISSUE THREAD

**Issue by edisch** [pastelsky/bundlephobia#26]
Searching for anything creates an application error:

eg. https://bundlephobia.com/result?p=redux@3.7.2

**Comment by padupuy** [comment]
There are also a lot of `TimeoutError This is taking unusually long. Check back in a couple of minutes?` :/

**Comment by pastelsky** [comment]
Looks like we got too many requests this month, and we're over heroku's limit. The API usage has shot up considerably and the server has been receiving a lot of bogus queries - as though someone integrated it into their editors and constantly pinging us. 
Unfortunately this means we'll have to wait for this month to end before the limit is replenished. I don't intend to break tools that are using this API, but if the number of invalid package requests (stuff like `../../utils/index.js`) continue, I'd have to limit usage using an API key or something.

**Comment by bertho-zero** [comment]
@pastelsky Maybe we can create a CLI version of this project?

**Comment by pastelsky** [comment]
Should be up now.

**Comment by edisch** [comment]
@pastelsky Time to start a SaaS company and move to Silicon Valley?
