### ISSUE TITLE
Package suggestion: url-join for normalize-url

### ISSUE THREAD

**Issue by sagar-gavhane** [pastelsky/bundlephobia#260]
**Package name**
normalize-url

**Alternative to**
url-join

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
Join all arguments together and normalize the resulting URL.

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
Thanks for your suggestion @sagar-gavhane.

While `normalize-url` and `url-join` both output a normalized version of the url they take, the utilities seem to have different purposes – `url-join` does more than just normalize.

I don't think they are 1:1 replacements for each other.
