### ISSUE TITLE
Package suggestion: spacetime  for moment

### ISSUE THREAD

**Issue by Roman-Vala** [pastelsky/bundlephobia#265]
**Package name**
spacetime
**Alternative to**

moment
**Quality check**

- [ x] Package has sufficient overlap in functionality to act as a replacement.
- [ x] Package is actively maintained, and/or stable for use.
- [ x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
`spacetime` is a timezone library. It's [already a suggestion in that category ](https://github.com/pastelsky/bundlephobia/blob/37d6c2f088f554e8e3a4eb3fff0a363892babf12/server/middlewares/similar-packages/fixtures.js#L424)
