### ISSUE TITLE
BuildError: clibuilder fails to build

### ISSUE THREAD

**Issue by unional** [pastelsky/bundlephobia#267]
## Package name

`clibuilder`

### Entire (stringified) error that I see in my browser console

```
/tmp/tmp-build/packages/build-clibuilder@6.0.0-TSg/node_modules/clibuilder/libm/plugin-cli/createPluginCli.js 5:41 Module parse failed: Unexpected token (5:41) File was processed with these loaders: * ./node_modules/shebang-loader/index.js You may need an additional loader to handle the result of these loaders. | import { pluginsCommand } from './pluginsCommand'; | export function createPluginCli(options) { > options.commands = options.commands ?? []; | options.commands.unshift(pluginsCommand); | const cwd = options.context?.cwd ?? process.cwd(); @ /tmp/tmp-build/packages/build-clibuilder@6.0.0-TSg/node_modules/clibuilder/libm/plugin-cli/index.js 1:0-34 1:0-34 @ /tmp/tmp-build/packages/build-clibuilder@6.0.0-TSg/node_modules/clibuilder/libm/index.js @ /tmp/tmp-build/packages/build-clibuilder@6.0.0-TSg/index.js
```

I'm using '@babel/plugin-proposal-nullish-coalescing-operator'

Likely the build on `bundlephobia` does not support it.

btw I also use '@babel/plugin-proposal-optional-chaining'

**Comment by unional** [comment]
Nevermind. I think that is not done correctly because NodeJS does not support them.
I need to transpile it down using babel instead of TypeScript.

**Comment by shrpne** [comment]
I have the same issue with native js and usage of optional-chaining.
I guess babel-preset-env should be used to process it.
My package: [minterjs-tx](https://bundlephobia.com/result?p=minterjs-tx)

@pastelsky please consider reopening this

**Comment by shrpne** [comment]
@pastelsky I believe update to babel ^7.8 should fix this type of BuildError

**Comment by pastelsky** [comment]
@shrpne Just pushed out an update that bumps up all of your build dependencies. Could you check if things work for you now? Both `minterjs-tx` and `clibuilder` are building fine.

**Comment by shrpne** [comment]
@pastelsky Looks like it still doesn't work. `minterjs-tx` builds because it doesn't have optional-chaining anymore.
But I have another package with optional-chaining https://bundlephobia.com/result?p=minter-js-sdk and it fails.

```/tmp/tmp-build/packages/build-minter-js-sdk@0.30.3-34u/node_modules/minter-js-sdk/src/api/post-tx.js 125:27 Module parse failed: Unexpected token (125:27) File was processed with these loaders: * ./node_modules/shebang-loader/index.js You may need an additional loader to handle the result of these loaders. | */ | function getTxResult(error) { > error = error.response?.data?.error; | // gate moves tx_result into root error, so check it too | return error && (error.tx_result || error); @ /tmp/tmp-build/packages/build-minter-js-sdk@0.30.3-34u/node_modules/minter-js-sdk/src/index.js 6:0-38 44:0-104:2 @ /tmp/tmp-build/packages/build-minter-js-sdk@0.30.3-34u/index.js```
