### ISSUE TITLE
Exports Analysis return all files with the same size

### ISSUE THREAD

**Issue by bluebill1049** [pastelsky/bundlephobia#268]
First of all, thank you for your amazing work @pastelsky and what a great tool that you have developed. <3

## Exports Analysis
<img width="1266" alt="Screen Shot 2020-01-07 at 10 45 31 pm" src="https://user-images.githubusercontent.com/10513364/71893337-6e669880-319f-11ea-9d16-75ed209bacb2.png">

For some reason, export analysis showing all the files with the same sizes, I am sure this is something I have configured wrong, wondering if you could give me a hand or guide on what to be done to fix it.

## Package name
react-hook-form

**Comment by ricokahler** [comment]
I'm a library author and I'm always wondering how this works (and how to reduce the size for each import!). Any advice or docs would be greatly appreciated.

PS: Echoing OP, bundlephobia is awesome.
