### ISSUE TITLE
Package suggestion: vanilla-lazyload for lazysizes

### ISSUE THREAD

**Issue by Jogai** [pastelsky/bundlephobia#269]
**vanilla-lazyload**

**Alternative to**
lazysizes

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Comment by pastelsky** [comment]
Thanks for the suggestion. Would be included in the next release.
