### ISSUE TITLE
Endless loading for "handsontable" library

### ISSUE THREAD

**Issue by ArturBaybulatov** [pastelsky/bundlephobia#27]
![image](https://user-images.githubusercontent.com/3109399/32780160-5be57c84-c951-11e7-824d-7573bc3fb6c3.png)

**Comment by pastelsky** [comment]
bundlephobia is hosted on heroku which has a hard limit of 30s to process requests. Since `handsontable` is a pretty large library, it seems to be taking longer than this.

That said, we've now improved the error message to better convey the timeout error instead of just hanging.

**Comment by ArturBaybulatov** [comment]
Great! Thanks
