### ISSUE TITLE
Package suggestion: Fielder for React based form builders & validators

### ISSUE THREAD

**Issue by andyrichardson** [pastelsky/bundlephobia#272]
**Package name**
Fielder

 - [repo](https://github.com/andyrichardson/fielder)
 - [docs](http://fielder.andyrichardson.dev/)

**Alternative to**
 - Formik
 - Hooked form

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
React based form builders & validators

**Comment by andyrichardson** [comment]
@pastelsky any chance you could take a look at this 🙏

**Comment by pastelsky** [comment]
Thanks for your suggestion. `React based Form` is a crowded category and we wish to keep suggestions limited to 4-5 for them to remain effective. We wouldn't be able to incorporate this at the moment.
