### ISSUE TITLE
BuildError for @vimeo/player

### ISSUE THREAD

**Issue by ende124** [pastelsky/bundlephobia#273]
**Describe the bug**
@vimeo/player gives a BuildError.
There is no stacktrace in the console. It just says there too that there is an builderror.

**To Reproduce**
Input `@vimeo/player` and see a BuildError-

**Expected behavior**
It should not give an BuildError.

**Comment by pastelsky** [comment]
This looks to be building successfully now. Might have been due to a temporary downtime if the stack trace was absent. Closing this for now, but feel free to open another issue if you face this again.
