### ISSUE TITLE
Package suggestion: vue-slick-carousel for vue-slick-carousel/vue-carousel

### ISSUE THREAD

**Issue by kyuwoo-choi** [pastelsky/bundlephobia#274]
**Package name**
vue-slick-carousel

**Alternative to**

vue-awesome-swiper
vue-carousel
vue-concise-slider
vue-agile

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
vue-carousel
```js
{
'vue-carousel': {
    name: 'Vue JS Sliders & Carousels',
    tags: [
      { tag: 'swipe', weight: Weight.MID },
      { tag: 'vue', weight: Weight.MAX },
      { tag: 'carousel', weight: Weight.MAX },
      { tag: 'slider', weight: Weight.MAX },
      { tag: 'swiper', weight: Weight.MAX },
    ],
    similar: ['vue-awesome-swiper', 'vue-carousel', 'vue-concise-slider','vue-agile', 'vue-slick-carousel']
  },
}
```

<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by kyuwoo-choi** [comment]
the existing comparison is based on vanilla carousel.
It should be compared to vue carousels

**Comment by pastelsky** [comment]
Thanks for the suggestion. This will be included in our next release.
