### ISSUE TITLE
Package suggestion: @reatom/core for redux / state-management

### ISSUE THREAD

**Issue by belozer** [pastelsky/bundlephobia#275]
**Package name**
@reatom/core

**Alternative to**
redux, mobx, storeon

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
state-management

**Comment by pastelsky** [comment]
We don't want to maintain an exhaustive list of packages for each category – that isn't very scalable. We aim to keep only the top 4-5 in each and hence the quality checks are essential for us to be able to offer packages as a suggestion.

The state management category is pretty saturated and doesn't appear that `@reatom/core` can dethrone any of the existing recommendations.

Thanks a lot for this suggestion, but it wouldn't be possible to include this.
