### ISSUE TITLE
BuildError: react-native-* fails to Unexpected token

### ISSUE THREAD

**Issue by retyui** [pastelsky/bundlephobia#279]
## react-native-stylex

A lot of React Native packages published on npm as ES modules, and it normal

But when I tried to get a bundlephobia report I faced with unexpected error that JSX syntax and `export` `import` declaration are invalid syntax and need to add a webpack loader to fix it

And It should be a babel-loader with
-  ~~[react-native-babel-preset](https://github.com/facebook/metro/tree/master/packages/metro-react-native-babel-preset)~~
- [metro-react-native-babel-preset](https://www.npmjs.com/package/metro-react-native-babel-preset)

### Entire (stringified) error that I see in my browser console

```
/tmp/tmp-build/packages/build-react-native-stylex@1.1.0-JI9/node_modules/react-native-stylex/lib/withStyles.js 6:19 

Module parse failed: Unexpected token (6:19) 
File was processed with these loaders: * ./node_modules/shebang-loader/index.js You may need an additional loader to handle the result of these loaders. 

| const WithStyles = (props, ref) => { 
| const styles = useStyles(); > return <Component {...props} ref={ref} styles={styles}/>; 
| }; 
| // @ts-ignore @ 

/tmp/tmp-build/packages/build-react-native-stylex@1.1.0-JI9/node_modules/react-native-stylex/lib/index.js 3:0-53 3:0-53 @ 
/tmp/tmp-build/packages/build-react-native-stylex@1.1.0-JI9/index.js
```

**Comment by talesdsp** [comment]
I'm facing a similar error with react-native too.

Output:
`tmp/tmp-build/packages/build-expo-ui-kit-6-C/node_modules/expo-ui-kit/src/Input.js 130:4 Module parse failed: Unexpected token (130:4) File was processed with these loaders: * ./node_modules/shebang-loader/index.js You may need an additional loader to handle the result of these loaders. | | return ( > <TextInput | ref={internalRef} | {...props} @ /tmp/tmp-build/packages/build-expo-ui-kit-6-C/node_modules/expo-ui-kit/src/index.js 4:0-28 7:0-44 @ /tmp/tmp-build/packages/build-expo-ui-kit-6-C/node_modules/expo-ui-kit/index.js @ /tmp/tmp-build/packages/build-expo-ui-kit-6-C/index.js`

**Comment by retyui** [comment]
seems no one care about it
