### ISSUE TITLE
Package suggestion: <alternative> immutable-js <package / category>

### ISSUE THREAD

**Issue by abduwaly** [pastelsky/bundlephobia#280]
**Package name**
[immutable-js](https://github.com/immutable-js/immutable-js)

**Alternative to**
Immer

**Quality check**

- [ ] Package has sufficient overlap in functionality to act as a replacement.
- [ ] Package is actively maintained, and/or stable for use.
- [ ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
Immutability

**Comment by pastelsky** [comment]
This is already a part of the "Immutable Data" category. See-

https://bundlephobia.com/result?p=immutable@4.0.0-rc.12
