### ISSUE TITLE
Package suggestion: dompurify for sanitize-html

### ISSUE THREAD

**Issue by delanebob** [pastelsky/bundlephobia#284]
**dompurify**
https://www.npmjs.com/package/dompurify

**Alternative to**
sanitize-html: https://www.npmjs.com/package/sanitize-html

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
Sanitization

**Comment by pastelsky** [comment]
Thanks for the suggestion. This will be added in the next release.
