### ISSUE TITLE
Package suggestion: vue-tiny-slider for vue-slick-carousel / VueJS Sliders & Carousels>

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [pastelsky/bundlephobia#285]
**Package name**
vue-tiny-slider

**Alternative to**
[vue-slick-carousel](https://github.com/viktorlarsson/vue-tiny-slider)
[vue-flickity](https://www.npmjs.com/package/vue-flickity)
[vue-awesome-swiper](https://github.com/surmon-china/vue-awesome-swiper)

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Comment by pastelsky** [comment]
Thanks for your suggestion. This library doesn't appear to be actively maintained looking at its issue backlog. We wouldn't be able to incorporate this at the moment.
