### ISSUE TITLE
Package suggestion: ReactN for Redux/State Managers

### ISSUE THREAD

**Issue by TuckerMassad** [pastelsky/bundlephobia#287]
**Package name**
Redux

**Alternative to**
ReactN

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
Thanks for your suggestion. State management is a crowded category and we wish to keep suggestions limited to 4-5 for them to remain effective. We wouldn't be able to incorporate this at the moment
