### ISSUE TITLE
TailwindCss

### ISSUE THREAD

**Issue by pxwee5** [pastelsky/bundlephobia#29]
Add support for tailwindcss? Would love to see how good it gets compressed. 

## Type
TimeoutError
The package took more than 30s to build and was aborted. This can happen if the package is very large and / or if the server is under heavy load.

## Package name
TailwindCSS

**Comment by pastelsky** [comment]
This is because in the project's package.json, the `main` field points to `lib/index`, which starts the build process. This is incorrect, and should ideally be pointing to the CSS/SCSS entry point.

**Comment by pastelsky** [comment]
Closing this since its not the use case bundlephobia aims to solve, unless the correct entry point is listed in package.json.
