### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ConsoleTVs** [pastelsky/bundlephobia#290]
## Type
Build Error

## Package name

Ultrabundle

### Entire error (stringified) I see in my browser console

main.bundle.js from Terser Invalid assignment [main.bundle.js:162234,17] at Q (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser/dist/bundle.min.js:1:19191) at c (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser/dist/bundle.min.js:1:27666) at Ye (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser/dist/bundle.min.js:1:49814) at Je (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser/dist/bundle.min.js:1:49895) at T (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser/dist/bundle.min.js:1:33561) at /var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser/dist/bundle.min.js:1:28816 at /var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser/dist/bundle.min.js:1:28397 at x (/var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser/dist/bundle.min.js:1:37878) at /var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser/dist/bundle.min.js:1:30009 at /var/www/bundlephobia/node_modules/package-build-stats/node_modules/terser/dist/bundle.min.js:1:28397

**Comment by pastelsky** [comment]
Bundlephobia is meant to be used for calculating sizes for libraries that might be shipped to clients. `Ultrabundle` is heavy and unlikely to be bundled in a client-side application. Moreover solving bundling errors for such tools can be tricky.

Solving for this is a low priority for us, however, you can use the [package-build-stats](https://github.com/pastelsky/package-build-stats) library and bundle it locally to get more details on why the bundling fails and submit a fix for the issue you see to either the library or to bundlephobia.
