### ISSUE TITLE
Package suggestion: hooked-form for formik/forms

### ISSUE THREAD

**Issue by JoviDeCroock** [pastelsky/bundlephobia#291]
**Hooked-form**

**Alternative to**
- formik
- formsy-react
- react-final-form

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [ ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
react-form

**Comment by pastelsky** [comment]
Thanks for the suggestion @JoviDeCroock, it looks like a neat library. `react-form` is a very crowded category, and we do not exhaustively want to list all such libraries here at the moment. 

I believe the ones that we list today are more widely used and we want to keep our suggestions focussed to a minimum (4-5), so we're not inclined to extend our recommendations as of now.
