### ISSUE TITLE
Package suggestion: chartist for chart.js

### ISSUE THREAD

**Issue by undestroyer** [pastelsky/bundlephobia#292]
**Package name**
[Chartist](https://www.npmjs.com/package/chartist)

**Alternative to**
chart.js

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**

general-purpose-charting

**Comment by pastelsky** [comment]
Thanks for your suggestion. This would be included in our next release.
