### ISSUE TITLE
Package suggestion: lottie-web for react-lottie

### ISSUE THREAD

**Issue by soonertrent** [pastelsky/bundlephobia#293]
**react-lottie**

**Alternative to**
lottie-web

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
Thanks for the suggestion, but I don't really believe that those two packages are functionally equivalent.
