### ISSUE TITLE
Package suggestion: react-select for downshift

### ISSUE THREAD

**Issue by antonydb** [pastelsky/bundlephobia#295]
**Package name**
react-select

**Alternative to**
downshift, react-autocomplete, react-autosuggest

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
react-autocomplete

**Comment by pastelsky** [comment]
Thanks for your suggestion. This will be included with the next release of Bundlephobia.
