### ISSUE TITLE
BuildError - Missing packages (e.g. vue-pure-lightbox)

### ISSUE THREAD

**Issue by simplenotezy** [pastelsky/bundlephobia#300]
Hi - I notice `vue-pure-lightbox` cannot be found. I'd love to see this here, to compare the sizes of similar libraries.

**Comment by simplenotezy** [comment]
Ah, the more I think about it, this must be a bug. Because it cannot find packages I could find a few days ago. So something must be wrong.

**Comment by pastelsky** [comment]
Was this the autocomplete not working, or did building the package give you a `PackageNotFoundError` ?

We currently use a third party index (https://npms.io) for the autocomplete and the problem might have been there.

**Comment by pastelsky** [comment]
Closing this since I can see this package now.
