### ISSUE TITLE
Installing the packaged failed.

### ISSUE THREAD

**Issue by sayjeyhi** [pastelsky/bundlephobia#302]
Hi,

Package `@snappmarket/ui@0.1.38` new version cannot build on Bundlephobia .
it could install with npm or yarn...

```javascript
{"error":{"code":"InstallError","message":"Installing the packaged failed.","details":{}}}
```

**Comment by DaniAkash** [comment]
Facing the same issue with [rex-state](https://bundlephobia.com/result?p=rex-state)

**Comment by DaniAkash** [comment]
Working for me now 👍

**Comment by pastelsky** [comment]
Feel free to re-open an issue if you see this again. Thanks!
