### ISSUE TITLE
build error react-toolbox

### ISSUE THREAD

**Issue by sayjeyhi** [pastelsky/bundlephobia#304]
I think some time bundle phobia servers are fully down, and now is one those times.
`react-toolbox` could not build and test on bundlephobia.

The service just saying : 
**BuildError**
Oops, something went wrong and we don't have an appropriate error for this. Open an issue maybe?

**Comment by Venryx** [comment]
Same issue for me, for all packages:
![](https://i.imgur.com/BkHtZ4S.png)

**Comment by Venryx** [comment]
Okay, it looks like if you wait long enough (like 5 minutes), eventually the results are available, after a page refresh:
![](https://i.imgur.com/E9kI1q2.png)

**Comment by sayjeyhi** [comment]
@Venryx actually it is not predictable

**Comment by pastelsky** [comment]
We were facing some downtime last week due to having run out disk space (oops!). This has been fixed now. Feel free to open a new issue if you see similar issues again.
