### ISSUE TITLE
site shows error message after reload.

### ISSUE THREAD

**Issue by OlegBrony** [pastelsky/bundlephobia#305]
1. open site
2. search for package (effector for example). 
3. reload page
![image](https://user-images.githubusercontent.com/19880334/75519831-d94c8700-5a0c-11ea-8e61-10dc601799a6.png)

**Comment by sandbox4013** [comment]
I'm unable to see rc-select package info with same BundleError:(
![image](https://user-images.githubusercontent.com/49528851/75541377-8384d880-5a26-11ea-8fde-c0604a49a936.png)

**Comment by pastelsky** [comment]
Working fine right now. Might have been due to a downtime we had a few days back.
