### ISSUE TITLE
BuildError: jose fails to retrieve details

### ISSUE THREAD

**Issue by joshuadiablito** [pastelsky/bundlephobia#306]
## jose
https://bundlephobia.com/result?p=jose@1.24.0
### Entire (stringified) error that I see in my browser console

```
error:
    code: "BuildError"
    message: "Oops, something went wrong and we don't have an appropriate error for this. Open an issue maybe?"
```
https://bundlephobia.com/api/size?package=jose@1.24.0&record=true 520 error

**Comment by pastelsky** [comment]
This was due to a temporary downtime bundlephobia was experiencing. This should be fine now.
