### ISSUE TITLE
Package suggestion: dinero.js for accounting

### ISSUE THREAD

**Issue by thorin** [pastelsky/bundlephobia#310]
**Package name**
dinero.js

**Alternative to**
currency.js, accounting

**Quality check**

- [ ] Package has sufficient overlap in functionality to act as a replacement.
- [ ] Package is actively maintained, and/or stable for use.
- [ ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
Number and Currency Formatting

**Comment by pastelsky** [comment]
Thanks for your suggestion. This will be added in the next release of Bundlephobia
