### ISSUE TITLE
Package suggestion: clsx for classnames

### ISSUE THREAD

**Issue by Akiyamka** [pastelsky/bundlephobia#316]
**Package name**
https://github.com/JedWatson/classnames
**Alternative to**

https://github.com/lukeed/clsx

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**

css-in-js

**Comment by pastelsky** [comment]
Thanks for your suggestion. This will be included in the next release of bundlephobia.
