### ISSUE TITLE
BuildError: api-viewer-element fails to build this package

### ISSUE THREAD

**Issue by web-padawan** [pastelsky/bundlephobia#320]
## Package name

`api-viewer-element` - any version starting from 0.3.6 (last correct version was 0.3.5)

### Entire (stringified) error that I see in my browser console

```
error:
code: "BuildError"
message: "Failed to build this package."
details:
name: "BuildError"
originalError:
operation: "PACKAGE_BUILD_STATS"
reason: "BUILD_SERVICE_UNREACHABLE"
url: "http://localhost:7002/size?p=api-viewer-element%400.3.6"
```

Note: `yarn.lock` was updated after `0.3.5`: https://github.com/web-padawan/api-viewer-element/commit/b2c4e0c910e129b02511f10e7ba985939d7baf29

**Comment by pastelsky** [comment]
`BUILD_SERVICE_UNREACHABLE` usually implies that one or more of your build worker processes were down. This might have been due to a service disruption caused by higher than usual traffic or another temporary issue that has since been resolved.

Thanks for taking time to report this issue.
