### ISSUE TITLE
Package suggestion: npn-slider for ng5-slider

### ISSUE THREAD

**Issue by mruffieux** [pastelsky/bundlephobia#322]
**Package name**
npn-slider

**Alternative to**
ng5-slider

**Quality check**

- [X] Package has sufficient overlap in functionality to act as a replacement.
- [X] Package is actively maintained, and/or stable for use.
- [ ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub. (ALMOST)

**Category**
Vanilla JS Sliders & Carousels

**Comment by pastelsky** [comment]
We don't want to maintain an exhaustive list of packages for each category – that isn't very scalable. We aim to keep only the top 4-5 in each and hence the quality checks are essential for us to be able to offer packages as a suggestion.

Thanks for the suggestion!
