### ISSUE TITLE
Show source

### ISSUE THREAD

**Issue by dy** [pastelsky/bundlephobia#324]
Is there any way to show minified package source? Sometimes that's useful info when optimizing source code to be well-minifiable.
Also the other times that is useful to just copy-paste that code, because running bundling setup any time one needs minified code is troublesome.

**Comment by pastelsky** [comment]
It is out of bundlephobia's scope to minify and show minified code – it isn't meant to act as a bundler. If however, you feel that you'd like to better understand how bundlephobia calculate its stats, you can use [the `package-build-stats` package ](https://github.com/pastelsky/package-build-stats) to see what the source compiles down to. (You'd have to [enable the WriteFilePlugin](https://github.com/pastelsky/package-build-stats/blob/master/src/webpack.config.js#L69))
