### ISSUE TITLE
Package suggestion: embla-carousel for Vanilla JS Sliders & Carousels

### ISSUE THREAD

**Issue by davidcetinkaya** [pastelsky/bundlephobia#328]
**Package name**
[Embla Carousel](https://github.com/davidcetinkaya/embla-carousel)

**Alternative to**
- flickity
- swiper
- slick-carousel
- glider-js

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
- Vanilla JS Sliders & Carousels

<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
Thanks for your suggestion. Vanilla JS Sliders & Carousels is a crowded category and we wish to keep suggestions limited to 4-5 for them to remain effective. We wouldn't be able to incorporate this at the moment.
