### ISSUE TITLE
Sizes chart alignment is wrong with long-ish release names

### ISSUE THREAD

**Issue by FezVrasta** [pastelsky/bundlephobia#331]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5382443/78527820-368ee180-77de-11ea-95c3-b008f3e417e6.png)

**To Reproduce**
Have a release name with more characters than the other.

**Expected behavior**
The chart should be correctly aligned

**Comment by pastelsky** [comment]
This issue is tracked as a part of #456. Thanks for taking out time to report this.
