### ISSUE TITLE
Package suggestion: velocity-animate for general purpose animation libraries

### ISSUE THREAD

**Issue by Nesuniken** [pastelsky/bundlephobia#338]
**velocity-animate**

**Alternative to**
GSAP

**Quality check**
- [X] Package has sufficient overlap in functionality to act as a replacement.
- [X] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.

**Category**
General-purpose animation libraries

**Comment by pastelsky** [comment]
Thanks for the suggestion. This would be added in the next release of Bundlephobia.
