### ISSUE TITLE
BuildError: several packages

### ISSUE THREAD

**Issue by wellyshen** [pastelsky/bundlephobia#339]
Hi, thank you for this service it's awesome. Recently I encounter the package "build error" for my several packages as below:

- [use-places-autocomplete](https://bundlephobia.com/result?p=use-places-autocomplete)
- [react-cool-portal](https://bundlephobia.com/result?p=react-cool-portal)
- [react-cool-onclickoutside](https://bundlephobia.com/result?p=react-cool-onclickoutside)
- [react-cool-inview](https://bundlephobia.com/result?p=react-cool-inview)

All of them got the same error message from Google Chrome console log

<img width="536" alt="螢幕快照 2020-04-14 上午12 07 44" src="https://user-images.githubusercontent.com/21308003/79137380-32b61d00-7de5-11ea-92d1-8091f1714b18.png">

**Comment by pastelsky** [comment]
This is because you ship with `.esm.js` files that are not compressible using terser js. Your output seems to be missing a semicolon before export.

Try using this –
https://xem.github.io/terser-online/

**Comment by wellyshen** [comment]
@pastelsky Thank you for telling me this bug. Seems `rollup-plugin-terser` set the `options.module` as `true` that cause the bug of the missed semicolon. I set the `options.module` as `false` to solve this problem.
