### ISSUE TITLE
BuildError "envelope" package

### ISSUE THREAD

**Issue by BramEsposito** [pastelsky/bundlephobia#34]
## Type
Bug

## Package name

envelope

### Entire error (stringified) I see in my browser console

BuildError: Failed to build this package.

(there is not a lot of info available for this error)

**Comment by mpeyper** [comment]
+1 I'm getting the same error for just about any package I request.

**Comment by pastelsky** [comment]
The build server was down for a while. Could you please check again?

**Comment by mpeyper** [comment]
@pastelsky seems to be working as expected now. Thanks!

**Comment by pastelsky** [comment]
Great. Closing this.
