### ISSUE TITLE
BuildError: react-giphy-searchbox

### ISSUE THREAD

**Issue by sergiop** [pastelsky/bundlephobia#343]
## Type
BuildError

## Package name
react-giphy-searchbox

### Entire error (stringified) I see in my browser console
```
{"error":{"code":"BuildError","message":"Failed to build this package.","details":{"name":"BuildError"}}}
```

**Comment by pastelsky** [comment]
I can see sizes for the last 15 versions of this library. Might have been due to a service downtime or another temporary issue.
