### ISSUE TITLE
Package suggestion: color2k, alternative for color-manipulation

### ISSUE THREAD

**Issue by ricokahler** [pastelsky/bundlephobia#344]
**Package name**

[`color2k`](https://github.com/ricokahler/color2k)

**Alternative to**

- tinycolor2
- chroma-js
- polished
- colors.js

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [ ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.
- [x] This package is a better alternative to what is already suggested for this category, or the category is new.

**Category**

[`color-manipulation`](https://github.com/pastelsky/bundlephobia/blob/e0b041b6f79118d68f13f014d4d4bce03537de2f/server/middlewares/similar-packages/fixtures.js#L35)

---

This lib is brand new but written with lots of tests and CI. Hope you'll consider add it in. Thanks a bunch!

https://color2k.com

**Comment by pastelsky** [comment]
Thanks for the suggestion. This would be added in the next release of Bundlephobia.
