### ISSUE TITLE
Wrong size for "events" package?

### ISSUE THREAD

**Issue by screendriver** [pastelsky/bundlephobia#347]
If you compare the [size](https://bundlephobia.com/result?p=mitt@1.2.0) of [mitt](https://github.com/developit/mitt) with the [size](https://bundlephobia.com/result?p=events@3.1.0) of [events](https://github.com/Gozala/events) you can see that `events` is smaller at bundlephobia.com. But if you look at the implementation of both you will see that `events` is bigger than `mitt`.

I'm just curious how the numbers are calculated and if there is maybe something wrong?

**Comment by pastelsky** [comment]
This occurs because `events` is the name of an in-built node library as well, and bundlephobia ignores the size of in-built modules. The size of `events` is very less because essentially, the entire package is ignored.
