### ISSUE TITLE
Package suggestion: react-form for formik, react-hook-form / React based form builders & validators

### ISSUE THREAD

**Issue by ankibalyan** [pastelsky/bundlephobia#349]
**Package name**: react-form

**Alternative to**: react-hook-form, formik

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.
- [x] This package is a better alternative to what is already suggested for this category, or the category is new.

**Category**: React based form builders & validators

<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
Thanks for the suggestion. This would be added in the next release of Bundlephobia.
