### ISSUE TITLE
Can't load vega package

### ISSUE THREAD

**Issue by WhoAteDaCake** [pastelsky/bundlephobia#35]
## Type

Cannot load package size
## Package name
`vega`

### Entire error (stringified) I see in my browser console
```
{"error":{"code":"BuildError","message":"Failed to build this package.","details":{"name":"BuildError"}}}
```

**Comment by pastelsky** [comment]
Seems to working fine for me now. Not sure what caused this. Feel free to reopen if you notice this happening again.
