### ISSUE TITLE
Chart disappears immediately

### ISSUE THREAD

**Issue by marcelltoth** [pastelsky/bundlephobia#350]
**Describe the bug**

When viewing the package _@stoplight/elements_ the size bar chart shows for a fraction of a second then disappears.

**To Reproduce**

Open https://bundlephobia.com/result?p=@stoplight/elements@5.2.2

Observe the chart flashing open then disappearing.

I can reproduce both in Chrome and in Firefox. Windows 10 1004.

**Expected behavior**

The chart displays correctly.

**Comment by pastelsky** [comment]
I can't reproduce this. Do this still happen for you @marcelltoth ?

**Comment by marcelltoth** [comment]
Not anymore.
