### ISSUE TITLE
Package suggestion: apexcharts for frappe-charts

### ISSUE THREAD

**Issue by Manviel** [pastelsky/bundlephobia#352]
**Package name**: [Apex charts](https://apexcharts.com/)

**Alternative to**

- Highcharts
- Recharts
- Frappe-charts

**Quality check**

- [x] Responsive
- [x] Interactive and Dynamic
- [x] Package has over 90 000 weekly downloads on NPM
- [x] High Performance
- [x] Smooth Animations
- [x] React, Angular, Vue integrations

**Category**: `charts`

**Comment by pastelsky** [comment]
Thanks for your suggestion. Charting is a crowded category and we wish to keep suggestions limited to 4-5 for them to remain effective. We do not aim to exhaustively list all packages in a category. Hence, we wouldn't be able to incorporate this at the moment.
