### ISSUE TITLE
Package suggestion: @ts-stack/markdown for marked

### ISSUE THREAD

**Issue by hckhanh** [pastelsky/bundlephobia#353]
**Package name**
@ts-stack/markdown

**Alternative to**
marked

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.
- [x] This package is a better alternative to what is already suggested for this category, or the category is new.

**Category**

<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
Thanks for the suggestion. "Markdown parsers" is a crowded category, and we want to keep suggestions limited to a maximum of 4-5. We would not be able to include this suggestion at the moment.
