### ISSUE TITLE
Package suggestion: <alternative> for <package / category>

### ISSUE THREAD

**Issue by AbhigyanKumar** [pastelsky/bundlephobia#354]
**Package name**
node-fetch@2.6.0
**Alternative to**
http

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.
- [ ] This package is a better alternative to what is already suggested for this category, or the category is new.

**Category**
The _http_ package is natively meant for performing https calls in NodeJS, whereas _node-fetch_ has a different approach of cloning the `fetch()` functionality to NodeJS Runtime. However, both perform the same functionality. Some tests show that `http` works slower than `node-fetch`, but `http` is more lightweight than `node-fetch`.

**Comment by pastelsky** [comment]
This is already a part of the `HTTP client libraries for Node.js` category. Closing this.
