### ISSUE TITLE
package do not load

### ISSUE THREAD

**Issue by gorazdkmet** [pastelsky/bundlephobia#355]
Failed to build this package.

![Snímka obrazovky 2020-06-08 o 10 03 10](https://user-images.githubusercontent.com/58269888/84006711-7e152380-a96f-11ea-93ab-73c3ad08dc5c.png)

**Comment by pastelsky** [comment]
Web Vitals compiles fine now —
https://bundlephobia.com/result?p=web-vitals@1.1.0
