### ISSUE TITLE
Case sensitive package names

### ISSUE THREAD

**Issue by FredyC** [pastelsky/bundlephobia#359]
**Describe the bug**

It surprised me as well, but apparently NPM is case sensitive

https://www.npmjs.com/package/webStorage
https://www.npmjs.com/package/webstorage

**To Reproduce**

https://bundlephobia.com/result?p=webStorage

**Expected behavior**

I should be shown stats for `webStorage` package, but I see `webstorage` instead.

**Comment by wopian** [comment]
Yeah...packages were case sensitive until 2017 when all-lowercase was enforced (unfortunately legacy packages kept their casing, but most of them seem unmaintained these days)

https://blog.npmjs.org/post/168978377570/new-package-moniker-rules#:~:text=In%20its%20earliest%20days%2C%20npm,registry%20and%20still%20in%20use.

**Comment by jfstn** [comment]
Hello 👋 

Came across the same issue with this [package](https://github.com/jfstn/Validator) I'm currently maintaining.

![image](https://user-images.githubusercontent.com/28389185/93665846-abdf2d80-fa71-11ea-969b-67d9d9a38d59.png)

I would say that if the idea is not to support packages that make use of capitalized letters then they should not appear when searching and should not be suggested. On the other hand I believe that we can not assume that these legacy packages are just not used or not maintained anymore.

Thanks

**Comment by pastelsky** [comment]
Case-sensitivity is supported by `package-build-stats`, which is bundlephobia's engine. I can see it gives right results for `webStorage` vs. `webstorage`. So does the API —

https://bundlephobia.com/api/size?package=webStorage
https://bundlephobia.com/api/size?package=webstorage

I believe the case conversion is happening on the frontend somewhere. Happy to take a fix for this.
