### ISSUE TITLE
Package suggestion: zod for schema-validation

### ISSUE THREAD

**Issue by avimar** [pastelsky/bundlephobia#367]
**Package name** zod

**Alternative to**
packages: joi yup ajv

**Quality check**

- [X] Package has sufficient overlap in functionality to act as a replacement.
- [X] Package is actively maintained, and/or stable for use.
- [X] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.  2886 weekly, 910 stars.
- [X] This package is a better alternative to what is already suggested for this category, or the category is new.

**Category**

schema-validation

**Comment by pastelsky** [comment]
Thanks for the suggestion. This would be included in the next release of bundlephobia.
