### ISSUE TITLE
[Bug] ethers package shows no dependencies on bundlephobia

### ISSUE THREAD

**Issue by bogdan** [pastelsky/bundlephobia#368]
**Describe the bug**

`ethers` package v5.0.3 is showing 29 dependencies on npm.
Bundlephobila shows no dependencies.

**To Reproduce**

Go to https://bundlephobia.com/result?p=ethers@5.0.3

**Expected behavior**

The page shows 29 dependencies just like https://www.npmjs.com/package/ethers
It is interesting that bundle-phobia-cli shows 29 dependencies correctly.

**Comment by pastelsky** [comment]
Thanks for taking time to report this issue.

I see that bundlephobia.com now correctly reports `29` as the dependency count, so I'm not sure what the issue was at the time, but it no longer exists.
