### ISSUE TITLE
inaccurate sizes 

### ISSUE THREAD

**Issue by kuldeepkeshwar** [pastelsky/bundlephobia#374]
for package [@filbert-js/core](https://github.com/kuldeepkeshwar/filbert-js) bundlephobia shows size `1.2kb` , [link](https://bundlephobia.com/result?p=@filbert-js/core)

Although unpkg reports `1.1kb` [link](https://img.badgesize.io/https://unpkg.com/@filbert-js/core@latest/dist/index.es.js?compression=gzip)

you can check the gzip badge [here](https://filbert-js.vercel.app/docs/introduction)

**Comment by pastelsky** [comment]
A difference of 100 bytes isn't something I'd worry about. Bundlephobia builds packages from scratch using webpack. Dist files inside the package might be using a different bundler / bundler configuration, and it is going to be very hard to not have a small difference in sizes.
