### ISSUE TITLE
Package suggestion: @filbert-js/core for CSS in JS libraries

### ISSUE THREAD

**Issue by kuldeepkeshwar** [pastelsky/bundlephobia#375]
**Package name**
`@filbert-js/core`
**Alternative to**

styled-components
emotion
jss
react-jss
linaria

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.
- [x] This package is a better alternative to what is already suggested for this category, or the category is new.

**Category**

<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
Thanks for the suggestion @kuldeepkeshwar. CSS-in-JS is a crowded category, and we want to keep suggestions limited to a maximum of 4-5. We would not be able to include this suggestion at the moment as this does not meet the criteria for inclusion.
