### ISSUE TITLE
Package suggestion: request for axios

### ISSUE THREAD

**Issue by sagar-gavhane** [pastelsky/bundlephobia#376]
**Package name**

request

**Alternative to**

axios

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.
- [x] This package is a better alternative to what is already suggested for this category, or the category is new.

**Category**

HTTP Client

<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by wopian** [comment]
Request is deprecated.

https://github.com/request/request/issues/3142

**Comment by pastelsky** [comment]
We only want to offer 4-5 effective alternatives. Since the request is deprecated, I wouldn't want to add it at the moment. Thanks!
