### ISSUE TITLE
A package is detected as not tree-shakable

### ISSUE THREAD

**Issue by vasilii-kovalev** [pastelsky/bundlephobia#377]
**Describe the bug**
A package is detected as not tree-shakable.

**To Reproduce**
1. Go to https://bundlephobia.com/result?p=hydrate-text@latest
2. Scroll down to "Exports Analysis" section
3. Observe message, that "This package does not export ES6 modules"

**Expected behavior**
A package is detected as fully tree-shakable.

**Additional Notes**
Checked the library with [agadoo](https://github.com/Rich-Harris/agadoo#using-agadoo).
The library does export ES6 modules. Here is [an example](https://unpkg.com/hydrate-text@1.1.2/lib/index.js) of an output file.
Besides speaking of this certain case, it would be great to know, how exactly this criterion is calculated, because the only information I've found out is [this release](https://github.com/pastelsky/bundlephobia/releases/tag/v1.2.0).
Thanks in advance.

**Comment by wereHamster** [comment]
The package doesn't have a "module" entry point.

**Comment by vasilii-kovalev** [comment]
Actually I besed my implementation on this check in the check libary, that I mentioned above:

https://github.com/Rich-Harris/agadoo/blob/b5489674bfa5f0cd9f8ebc2a8dd41e05dfadaa7d/agadoo#L29

It means, that `main` field is OK as well, not `module` only.

**Comment by wereHamster** [comment]
That check is not 100% accurate. You'd have to look at the actual code in webpack, rollup, parcel etc to see how they behave, what their conditions are for determining whether a package is tree-shakeable.

Furthermore, agadoo doesn't respect the new [Node.js v13+ "exports" field in package.json](https://nodejs.org/api/esm.html#esm_package_entry_points), which will be used in the future by bundlers.

**Comment by vasilii-kovalev** [comment]
@wereHamster
Yes, defining "module" field helped, thanks!
Also I found out, that adding `"sideEffects": false` also marked the library as dependency-free and allowed to see information in "Exports Analysis" section (though I don't use Webpack).

Only one thing I'd like to mention now is that https://bundlephobia.com/result?p=hydrate-text@latest is resolved to v.1.1.2, but https://bundlephobia.com/result?p=hydrate-text and `npm i hydrate-text@latest` are resolved to v.1.1.4 (trully the latest one).

**Comment by vasilii-kovalev** [comment]
Anyway, closing the ticket since the original issue is resolved.
