### ISSUE TITLE
Better support for Ember addons

### ISSUE THREAD

**Issue by Turbo87** [pastelsky/bundlephobia#38]
## Type
Feature Request

It would be awesome if this package had better support for Ember addons. Ember addons only bundle a certain subset of files into a browser package, so measuring all of the JS files in the project is resulting in wrong numbers. As a first step I would propose this solution:

- check if `package.json` contains an `ember-addon` "keyword"
- if the keyword was found only files in the `app` and `addon` folders are considered for the final browser weight

**Comment by pastelsky** [comment]
BundlePhobia does not show sizes of all JavaScript files in a project. It will only show you the bundle size using the entry point that is specified in package.json. Can you give me names of a few sample add-ons that exhibit this issue?

**Comment by Turbo87** [comment]
The problem is that for Ember addons the entry file is a Node.js-land file that defines some build pipeline related things. The actual code that is shipped to the browser is mostly unrelated to that file.

One relatively simple example is https://github.com/jmurphyau/ember-truth-helpers, you can find more on https://emberobserver.com

**Comment by pastelsky** [comment]
I don't think special casing ember-addons is a solution for this. Some addons like `ember-moment` clearly depend on another package (moment in this case), and finding its size makes more sense. 

Maintaining a list of such exceptions would not be very plausible, and lead to inconsistent behavior.

**Comment by Turbo87** [comment]
I agree that this can be more complicated in some cases and my suggestion above only works for the less sophisticated addons, but it would still be better than the wrong numbers that are currently being shown because building the addons using webpack simply does not result in correct numbers.

A more correct way would be generating an Ember project, measuring file size, adding the addon and then measuring the file size again, but that is obviously a more complicated solution.

Would it make sense to at least show a "this is an Ember addon and the numbers here are likely incorrect" warning if the `ember-addon` keyword exists for a package?

**Comment by pastelsky** [comment]
The numbers we're showing here aren't wrong per se. We're just being agnostic about the intention of the package. It would be upto the developers to interpret these results depending on the context of the package.
