### ISSUE TITLE
Package suggestion: redaxios for axios

### ISSUE THREAD

**Issue by belchior** [pastelsky/bundlephobia#381]
**Package name**
redaxios

**Alternative to**
axios

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.
- [x] This package is a better alternative to what is already suggested for this category, or the category is new.

**Comment by pastelsky** [comment]
Thanks for the suggestion @belchior. HTTP clients is a crowded category, and we want to keep suggestions limited to a maximum of 4-5. We would not be able to include this suggestion at the moment.
