### ISSUE TITLE
Package suggestion: <uplot> for <lightweight-charts / General purpose Charting libraries>

### ISSUE THREAD

**Issue by itssumitrai** [pastelsky/bundlephobia#385]
**Package name**

uplot

**Alternative to**

lightweight-charts 
chart.js
frappe-charts
echarts
highcharts

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.
- [x] This package is a better alternative to what is already suggested for this category, or the category is new.

**Category**

General purpose Charting libraries

<!-- Suggest an existing/new category that this package belongs to. Eg. Date Time formatting, Natural language processing etc. See - 

https://github.com/pastelsky/bundlephobia/blob/bundlephobia/server/middlewares/similar-packages/fixtures.js 

for a list of existing packages and categories.

**Comment by pastelsky** [comment]
Thanks for your suggestion. This will be included with the next release of Bundlephobia.
