### ISSUE TITLE
Package suggestion: frisbee for `HTTP client libraries for Node.js`

### ISSUE THREAD

**Issue by Shair17** [pastelsky/bundlephobia#403]
**Frisbee**

**Axios**

**Quality check**

- [ ] Package has sufficient overlap in functionality to act as a replacement.
- [ ] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.
- [x] This package is a better alternative to what is already suggested for this category (please explain why), or the category is new.

**Comment by pastelsky** [comment]
Thanks for the suggestion. HTTP Clients is a crowded category, and we want to keep suggestions limited to a maximum of 4-5. We would not be able to include this suggestion at the moment as this does not meet our criteria for inclusion.
