### ISSUE TITLE
Getting only 500 responses

### ISSUE THREAD

**Issue by marvinhagemeister** [pastelsky/bundlephobia#41]
## Type: Bug
Getting a `500` whenever I enter a search result. Same with the cli.

## Package name

Not related to a particular package, seems to be an issue with `zeit`

### Entire error (stringified) I see in my browser console

```bash
bundle-phobia react-router
Error happened: invalid json response body at https://bundlephobia.com/api/size?package=react-router reason: Unexpected token A in JSON at position 0
```

**Comment by pastelsky** [comment]
Should be working now. This probably occurred due to an out of memory error on the build server.
