### ISSUE TITLE
Not including all dependencies?

### ISSUE THREAD

**Issue by broofa** [pastelsky/bundlephobia#411]
Hey folks, author of http://npm.broofa.com here.  I'm very stoked to use this service, however in testing I'm seeing the following issue...

When I query BundlePhobia to get bundle information the response appears to be missing a lot of the dependencies that I would expect.  For example:

| package | dependency count (npm.broofa.com) | dependency count (BundlePhobia) |
|---|---|---|
| request | [47](http://npm.broofa.com/?q=request) | [20](https://bundlephobia.com/api/size?package=request) |
| webpack | [313](http://npm.broofa.com/?q=webpack) | [23](https://bundlephobia.com/api/size?package=webpack) |
| express | [51](http://npm.broofa.com/?q=webpack) | [30](https://bundlephobia.com/api/size?package=webpack) |

http://npm.anvaka.com (which I'm not affiliated with) reports a similar number of dependencies as my tool, fwiw.

Any idea what's going on here?

**Comment by wopian** [comment]
Based on my own packages on npm, I believe bundlephobia shows only the direct dependencies listed in package.json. With the import size of sub-dependencies counting to the size of the top-level dependency.

**Comment by broofa** [comment]
[Closing out issues I authored that appear to be stagnant.]
