### ISSUE TITLE
BuildError: Failed to build this package

### ISSUE THREAD

**Issue by dhruvdutt** [pastelsky/bundlephobia#42]
## Type
Bug

## Package name
[`@appbaseio/reactivesearch`
](https://www.npmjs.com/package/@appbaseio/reactivesearch)
### Entire error (stringified) I see in my browser console
`{code: "BuildError", message: "Failed to build this package.", details: {name: "BuildError"}}`

Also, tried with [bundle-phobia-cli](https://github.com/AdrieanKhisbe/bundle-phobia-cli)
![image](https://user-images.githubusercontent.com/5961873/34686044-5493aec4-f4d0-11e7-88d4-a492a7faefe3.png)

**Comment by pastelsky** [comment]
Build server stopped due to an out of memory error. Should be working now.
