### ISSUE TITLE
Image caching is too aggressive

### ISSUE THREAD

**Issue by jonahsnider** [pastelsky/bundlephobia#424]
**Describe the bug**

When using an image URL like `https://bundlephobia.com/api/stats-image?name=convert&version=1.0.1&wide=true` for a version that isn't published the image returns a placeholder, but the placeholder gets cached. After the version is published the placeholder image stays cached.

**To Reproduce**

Visit an image URL for a version that didn't exist at image generation time.

Example: `https://bundlephobia.com/api/stats-image?name=convert&version=999.999.999&wide=true`

https://github.com/pastelsky/bundlephobia/blob/a6046721fad9aaac2a78d9e00ac2e3e71ebd43b1/server/middlewares/generateImg.middleware.js#L30-L33

**Expected behavior**

There should be a much shorter cache period for placeholder images.

**Comment by pastelsky** [comment]
Thanks for raising the issue. Happy to take a fix for this — should be relatively straightforward.
