### ISSUE TITLE
BuildError: @yaireo/color-picker fails to build 

### ISSUE THREAD

**Issue by yairEO** [pastelsky/bundlephobia#443]
## [@yaireo/color-picker](https://www.npmjs.com/package/@yaireo/color-picker)

![image](https://user-images.githubusercontent.com/845031/102638178-c653a080-415f-11eb-9c1e-bd70efccc6c5.png)

maybe it's because I have [`np`](https://github.com/sindresorhus/np#config) property in `package.json`...?

![image](https://user-images.githubusercontent.com/845031/102638374-0d419600-4160-11eb-9390-51541170b76f.png)

Thank you!

**Comment by pastelsky** [comment]
Your library ships with ultra-modern JS features like nullish coalasceing, which probably isn't supported by Webpack / Acorn. 

Since its usually recommended to transpile libraries to ES5 / ES6, and bundlephobia does not make use of babel, this isn't something we can support until webpack does.

**Comment by yairEO** [comment]
@pastelsky - thank you for your time
