### ISSUE TITLE
Unexplained BuildError

### ISSUE THREAD

**Issue by jaydenseric** [pastelsky/bundlephobia#45]
## Type

Bug? Latest versions of several of my packages display `BuildError`, without a useful trace or explanation.

## Package name

- https://bundlephobia.com/result?p=extract-files
- https://bundlephobia.com/result?p=apollo-upload-client
- https://bundlephobia.com/result?p=apollo-upload-server

### Entire error (stringified) I see in my browser console

<img width="700" alt="screen shot 2018-01-16 at 1 14 15 am" src="https://user-images.githubusercontent.com/1754873/34946355-aa4f419a-fa5a-11e7-84dc-4dbe427cc361.png">

Here is the repo for `apollo-upload-client`: https://github.com/jaydenseric/apollo-upload-client.

**Comment by Raiondesu** [comment]
@jaydenseric, this seems to be related to #43

**Comment by pastelsky** [comment]
Should be fixed now, zeit now were having a few problems that have been resolved.
