### ISSUE TITLE
Incorrect GitHub repo link

### ISSUE THREAD

**Issue by dwelle** [pastelsky/bundlephobia#462]
**Describe the bug**

Many packages have incorrect link to their GitHub repos.

**To Reproduce**

https://bundlephobia.com/result?p=globalthis@1.0.1

![image](https://user-images.githubusercontent.com/5153846/105186721-493a9300-5b32-11eb-8774-722a5bd72242.png)

Don't have time right now to check other packages, but I've noticed this often enough.

**Expected behavior**

Should link to https://github.com/es-shims/globalThis

**Comment by abhijit-hota** [comment]
It's correct for me.

**Comment by dwelle** [comment]
It is now :thinking:. I'll reopen when I come across it again.
