### ISSUE TITLE
BuildError: @packula/router: Failed to build this package.

### ISSUE THREAD

**Issue by ezzatron** [pastelsky/bundlephobia#489]
- Previous versions were working
- `package-build-stats` is working
- `bundle-phobia-cli` is working

## Package name

[@packula/router](https://bundlephobia.com/result?p=@packula/router)

### Entire (stringified) error that I see in my browser console

```json
{
  "error": {
    "code": "BuildError",
    "message": "Failed to build this package.",
    "details": {
      "name": "BuildError"
    }
  }
}
```

**Comment by josuemontano** [comment]
Same for `@magicbell/magicbell-react`, this request returns 500: https://bundlephobia.com/api/size?package=@magicbell/magicbell-react&record=true

Thanks for this amazing product btw!

**Comment by mathix420** [comment]
Same for `vuito` => https://bundlephobia.com/api/size?package=vuito@0.0.7
