### ISSUE TITLE
Cannot find scoped packages

### ISSUE THREAD

**Issue by rmariuzzo** [pastelsky/bundlephobia#50]
## Type
Feature Request

## Package name
 - `@devexpress/dx-react-core`
 - `@elemental/link`
 - `@react-spectre/button`

### Entire error (stringified) I see in my browser console
> PackageNotFoundError
> The package you were looking for doesn't exist.

**Comment by frenic** [comment]
Same here for `@glitz/core`. It worked before. It only works if I explicitly add a version like `@glitz/core@1.0.0`.

**Comment by pastelsky** [comment]
This should be fixed now.

**Comment by aleclarson** [comment]
@pastelsky  I'm seeing this again. 😢

**Comment by aleclarson** [comment]
I put in the badge and pushed to Github __before__ publishing to NPM, so maybe the caching layer isn't being invalidated correctly?

**Comment by pastelsky** [comment]
Looks like it's working now. If you tried making a request before publishing the package, it's possible that the failure was cached for a small time.
