### ISSUE TITLE
BuildError: react-native-countdown-circle-timer fails to build this package

### ISSUE THREAD

**Issue by vydimitrov** [pastelsky/bundlephobia#503]
##  react-native-countdown-circle-timer

- [Repo react-native-countdown-circle-timer](https://github.com/vydimitrov/react-countdown-circle-timer/tree/master/packages/mobile#react-native-countdown-circle-timer)
- [Bundlephobia link](https://bundlephobia.com/result?p=react-native-countdown-circle-timer) 

### Entire (stringified) error that I see in my browser console
```
{
    "error": {
        "code": "BuildError",
        "message": "Failed to build this package.",
        "details": {
            "name": "BuildError"
        }
    }
}
```
### Additional information
I am getting a build error on my react-native-countdown-circle-timer for version 2.5.1. There are no issues with version 2.5.0. In 2.5.1 I updated several devDependecies I am really not sure why it fails in 2.5.1. 

I am able to build the package locally and in ExpoSnack works as expected in 2.5.1. I'd appreciate it if you can share with me a bit more details on why Bundlephobia fails to build it.

P.S.
I am a big fan of Bundlephobia and every time I add a new package to a project I check it and compare it in Bundlephobia. Thank you for the great product.

**Comment by xobotyi** [comment]
Same stuff https://bundlephobia.com/result?p=@react-hookz/web

**Comment by vydimitrov** [comment]
This is resolved now! Thanks.
