### ISSUE TITLE
Doesn't install peer dependencies of dependencies

### ISSUE THREAD

**Issue by jaydenseric** [pastelsky/bundlephobia#51]
## Type

Bug.

## Package name

https://bundlephobia.com/result?p=apollo-upload-client

### Entire error (stringified) I see in my browser console

<img width="1168" alt="screen shot 2018-02-16 at 6 33 56 pm" src="https://user-images.githubusercontent.com/1754873/36297650-040130da-1348-11e8-8390-71484fe82a12.png">

**Comment by pastelsky** [comment]
Installing `peerDependencies` of a dependency should be the job of the client. 
In this case, `apollo-upload-client` happens to be the client, and I'm not sure if the `peerDependency` chain can be passed on to the client of `apollo-upload-client`.

**Comment by jaydenseric** [comment]
This is effecting official Apollo packages too, see https://bundlephobia.com/result?p=apollo-boost

**Comment by pastelsky** [comment]
See https://github.com/pastelsky/bundlephobia/issues/55#issuecomment-371487670
