### ISSUE TITLE
BuildError Failed to build this package. <retractable>

### ISSUE THREAD

**Issue by sauerm1** [pastelsky/bundlephobia#515]
## Type

bug

## Package name
retractable

### Entire error (stringified) I see in my browser console
{"error":{"code":"BuildError","message":"Failed to build this package.","details":{"name":"BuildError"}}}

**Comment by brocococonut** [comment]
Likely related to #530

**Comment by pastelsky** [comment]
This works now, closing the issue. Thanks for your patience.
Try it out —
https://bundlephobia.com/package/retractable@1.16.2
