### ISSUE TITLE
Package suggestion: <package-name> for `General purpose date-time utilities`

### ISSUE THREAD

**Issue by emilioSp** [pastelsky/bundlephobia#517]
**Package name**
dayjs

**Alternative to**
luxon, moment, date-fns

**Quality check**

- [ x] Package has sufficient overlap in functionality to act as a replacement.
- [ x] Package is actively maintained, and/or stable for use.
- [ x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.
- [ x] This package is a better alternative to what is already suggested for this category (please explain why), or the category is new.

**Comment by mupkoo** [comment]
Isn't this what you are looking for https://bundlephobia.com/result?p=dayjs@1.10.4?

**Comment by emilioSp** [comment]
Yes, sorry. My mistake.
