### ISSUE TITLE
<error-name>: <package-name> fails to <condition>

### ISSUE THREAD

**Issue by SahidMiller** [pastelsky/bundlephobia#519]
## Package name

[@sahidmiller/hdnode](https://www.npmjs.com/package/@sahidmiller/hdnode)

I'm submitting this ticket because I'm confused and needing some guidance. When I import the above project into a local clean project, everything seems fine -- importing and calling functions -- yet, it's not building on bundlephobia! I'd like some help so I everyone can see how lightweight this package is, God willing. Thank you!

### Entire (stringified) error that I see in my browser console

```{
error: {code: "BuildError", message: "Failed to build this package.", details: {name: "BuildError"}}
code: "BuildError"
details: {name: "BuildError"}
name: "BuildError"
message: "Failed to build this package."
}```

**Comment by marcin1357** [comment]
sob., 22 maj 2021, 15:42 użytkownik SahidMiller ***@***.***>
napisał:
