### ISSUE TITLE
Idenfity if a package has a `sideEffects: false` field in package.json

### ISSUE THREAD

**Issue by TheLarkInn** [pastelsky/bundlephobia#52]
## Type

Feature Request

With webpack v4 around the corner, it would be awesome to denote to users searching for packages if their package (in addition to using the "module" field), also is "sideEffect free". We have package authors (see lodash-es) annotate this using a new field called "sideEffects: false". If this is set, webpack can perform even deeper optimizations to a library using ESM. (Also builds are faster because we skip evaluation of those unused exports).

**Comment by TheLarkInn** [comment]
Potentially could add the annotation here: https://github.com/pastelsky/bundlephobia/blob/d8202a921909ebe2a2638f76a0a795ea08d307f8/index.js#L316-L324

**Comment by pastelsky** [comment]
Hi @TheLarkInn. Thanks for writing in. What kind of improvements in size does one generally see when using a sideEffects:true package versus otherwise? Also, which webpack versions support this at the moment?

**Comment by TheLarkInn** [comment]
Hi there! The sizes can be incredibly significant. With lodash-es, a single import with sideEffects: false now in their package.json takes a 60kb hit to 1-2kb. However not every library will exhibit this behavior. Also it will be as of webpack 4 and on.

**Comment by pastelsky** [comment]
> With lodash-es, a single import with sideEffects: false now in their package.json takes a 60kb hit to 1-2kb
Does the difference hold even if `jsnext:main` / `module` fields are used? i.e.

**Comment by pastelsky** [comment]
I've added supports for indexing the `sideEffects` field for all new package searches. Will add support for surfacing this in the UI when webpack@4 becomes stable.

**Comment by machineloop** [comment]
I believe Wepback@4 has been released, is this available?

**Comment by pastelsky** [comment]
This is available in the quick info bar just below the search input. 🎊
