### ISSUE TITLE
BuildError @reason-native/rely

### ISSUE THREAD

**Issue by Conaclos** [pastelsky/bundlephobia#522]
BuildError "Failed to build this package" of [@reason-native/rely](https://reason-native.com/docs/rely/).

I tried with `bundle-phobia-cli` and it fails:
```sh
npx bundle-phobia '@reason-native/rely'                                    
✖ resolving @reason-native/rely failed: Failed to build this package.
bundle-phobia failed: Failed to build this package.
```

**Comment by pastelsky** [comment]
This package lacks a main-file and is written in reason. 
Bundlephobia does not support compilation of reason, nor does it intend to in the near future to keep our operations light.
Thanks for filing an issue.
