### ISSUE TITLE
Clarify "Emerging 3G"

### ISSUE THREAD

**Issue by robations** [pastelsky/bundlephobia#525]
**Please describe the feature/suggestion**

The UI says "Emerging 3G", in giving an estimate for the bundle download time.

What does "emerging" mean? Can this be explained further? Does this mean in "emerging markets"? E.g. developing countries? Is the "50 kB/s" figure based on some kind of global usage figure?

**Describe the solution you'd like**

Perhaps it could say "3G" or the (i) box could say "3G is still the most common mobile data protocol in emerging markets [1]" ?

This might help frame the download estimates in the correct context.

It might also be useful to show JS parse times on various phones, but I suppose that would be a separate suggestion :)

**Describe any alternatives you've considered**

n/a

**Comment by pastelsky** [comment]
This was picked up from webpagetest.org. But 2G seems redundant now.
