### ISSUE TITLE
Bars incorrectly ordered

### ISSUE THREAD

**Issue by raulsebastianmihaila** [pastelsky/bundlephobia#53]
## Type
Bug / Feature Request

## Package name
crizmas-form

I was thinking that the bars were supposed to be ordered based on the version. However, in case of crizmas-form 0.2.4 is before 0.2.3, 0.2.3 is before 0.1.2, 1.0.0 is before 0.2.10, etc. The order is not reversed either, for instance 0.2.2 is before 0.2.4 (which I assume is correct).

**Comment by pastelsky** [comment]
Seems to be fixed now, closing.
