### ISSUE TITLE
BuildError: react-native-unicons Failed to build this package.

### ISSUE THREAD

**Issue by FDiskas** [pastelsky/bundlephobia#548]
## Package name

package: [react-native-unicons](https://www.npmjs.com/package/react-native-unicons)
Repository: https://github.com/FDiskas/react-native-unicons
bundlephobia: https://bundlephobia.com/package/react-native-unicons

### Entire (stringified) error that I see in my browser console

```
{
    "error": {
        "code": "BuildError",
        "message": "Failed to build this package.",
        "details": {
            "name": "BuildError"
        }
    }
}
```

**Comment by Halfi** [comment]
Same here:
[npm](https://www.npmjs.com/package/russian-requisites-validation)
[repo](https://github.com/Halfi/russian-requisites-validation)
[bundlephobia](https://bundlephobia.com/package/russian-requisites-validation@1.0.1)

**Comment by pastelsky** [comment]
Bundlephobia does not yet support react-native packages. Follow this issue for more updates —
https://github.com/pastelsky/package-build-stats/issues/43
