### ISSUE TITLE
Package suggestion: @tomiocodes/uuid for `Unique ID generators`

### ISSUE THREAD

**Issue by 1chiSensei** [pastelsky/bundlephobia#551]
**Package name**
@tomiocodes/uuid

**Alternative to**
uuid, nanoid

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [ ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.
- [x] This package is a better alternative to what is already suggested for this category (please explain why), or the category is new.

The package is relatively faster because it uses a Node.js binding.

**Comment by pastelsky** [comment]
Thanks for the suggestion. This is a crowded category, and we want to keep suggestions limited to a maximum of 4-5. We would not be able to include this suggestion at the moment, since this does not meet the checklist criteria required.
