### ISSUE TITLE
Build Error: three fails to build

### ISSUE THREAD

**Issue by mrdoob** [pastelsky/bundlephobia#559]
## Package name

https://bundlephobia.com/package/three

### Entire (stringified) error that I see in my browser console

"Failed to build this package."

<img width="859" alt="Screen Shot 2021-08-27 at 12 50 46 PM" src="https://user-images.githubusercontent.com/97088/131116326-79da58ca-97a9-467b-bfa9-a90392fc4ff7.png">

I suspect it is because we tried using [private class fields](https://caniuse.com/mdn-javascript_classes_private_class_fields).

More info: https://github.com/mrdoob/three.js/issues/22437

**Comment by marcofugaro** [comment]
This issue can be closed, it was fixed [as mentioned here](https://github.com/pastelsky/bundlephobia/issues/413#issuecomment-1190989112)
