### ISSUE TITLE
webpack-serve fails on Node v9 built-in dependency

### ISSUE THREAD

**Issue by shellscape** [pastelsky/bundlephobia#56]
## Type
Bug

## Package name
webpack-serve

### Entire error (stringified) I see in my browser console

I took it one further as the API was throwing a 504. https://bundlephobia.com/api/size?package=webpack-serve&record=true produces:

```
{
  "error":{
    "code":"MissingDependencyError",
    "message":"This package (or this version) uses `<code>http2</code>`, but does not specify them<br /> either as a dependency or a peer dependency",
    "details":{
      "name":"MissingDependencyError",
      "originalError":[
        "ModuleNotFoundError: Module not found: Error: Can't resolve 'http2' in '/tmp/tmp-build/node_modules/webpack-serve/lib'"
      ],
      "extra":{
        "missingModules":[
          "http2"
        ]
      }
    }
  }
}
```

This one is fun because `http2` is a Node v9+ built-in. So it would suggest that the service platform the site is running on needs a node bump, or needs to be aware of new built-ins. Or this may be another case of the service being too tricky and overly aggressive checking dependencies.

**Comment by pastelsky** [comment]
Yes, internals such as this need to be mocked out. Will add it in the next release.

**Comment by pastelsky** [comment]
Let's track this at #74 .
