### ISSUE TITLE
Package suggestion: grafico-ql for `HTTP client libraries for Browser`

### ISSUE THREAD

**Issue by d3mo17** [pastelsky/bundlephobia#561]
**Package name**
grafico-ql

**Alternative to**
graphql-request

**Quality check**

- [*] Package has sufficient overlap in functionality to act as a replacement.
- [*] Package is actively maintained, and/or stable for use.
- [ ] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.
- [*] This package is a better alternative to what is already suggested for this category (please explain why), or the category is new.

It's smaller in size and has no dependencies

**Comment by pastelsky** [comment]
Thanks for the suggestion. This is a crowded category, and we want to keep suggestions limited to a maximum of 4-5. We would not be able to include this suggestion at the moment, since this does not meet the checklist criteria required.
