### ISSUE TITLE
prettier build error

### ISSUE THREAD

**Issue by dhruvdutt** [pastelsky/bundlephobia#58]
## Type
Bug :bug: 

## Package name
[prettier](https://www.npmjs.com/package/prettier)

### Entire error
```
BuildError
Failed to build this package.

/tmp/tmp-build/node_modules/prettier/index.js
Module parse failed: Invalid labeled declaration (4045:8)
You may need an appropriate loader to handle this file type.
|     }
|     _token_stack:
|         var lex = function () {
|             var token;
|             token = lexer.lex() || EOF;
@ /tmp/tmp-build/entries/index-prettier.js 1:11-30"
```

**Comment by pastelsky** [comment]
Calculating bundle sizes is useful primarily for front end dependencies. I can't think of a use case when you'd want to bundle prettier. PRs to fix this are welcome, though it is not a very high on priority.

**Comment by pastelsky** [comment]
This works now, so closing this.

**Comment by dhruvdutt** [comment]
> Calculating bundle sizes is useful primarily for front end dependencies. I can't think of a use case when you'd want to bundle prettier. PRs to fix this are welcome, though it is not high on priority.

https://github.com/webpack/webpack-cli/blob/c3ab11b2d9738c966a1854f5fa4041c013bcc8d6/packages/utils/package.json#L23

webpack-cli bundles `prettier` to prettify generation of new webpack config files.
