### ISSUE TITLE
houston-ui@0.41.5 failing to install

### ISSUE THREAD

**Issue by chriscorrales** [pastelsky/bundlephobia#582]
## Type
lastest version of @eduzz/houston-ui is failing to install. Follow link: https://bundlephobia.com/package/@eduzz/houston-ui

## Package name
houston-ui@0.41.5

### Entire error (stringified) I see in my browser console
​
code: "InstallError"
​​
details: Object {  }
​​
message: "Installing the packaged failed."

**Comment by omarryhan** [comment]
It seems that this issue is affecting all packages, any updates?
