### ISSUE TITLE
Doesn't bundle optional chaining operators and other ES6 symbols

### ISSUE THREAD

**Issue by dy** [pastelsky/bundlephobia#597]
We have some modern syntax in subscript, and bundlephobia can't bundle, see [stacktrace](https://bundlephobia.com/package/subscript@6.0.1)

**Expected behavior**

Just make last ES work, I guess bumping deps is enough

**Comment by pastelsky** [comment]
Please follow https://github.com/pastelsky/bundlephobia/issues/530#issuecomment-1003571659 for update on modern ES features

**Comment by pastelsky** [comment]
This works now, closing the issue. Thanks for your patience.
Try it out —
https://bundlephobia.com/package/subscript@6.0.1

I'm not sure if your library uses non-standard imports though as I see the bundler is having an issue locating a path.
