### ISSUE TITLE
Retrigger "saved" build?

### ISSUE THREAD

**Issue by vincentaudebert** [pastelsky/bundlephobia#60]
On the main UI: https://bundlephobia.com/result?p=react-accessible-accordion@2.3.0

I triggered the build too early after publishing (mirrors weren't all refreshed?) and it shows the same result than the previous version. I checked later on with another bundle checker and it's definitely much smaller.

I guess now the result is cached and will always show this result for this version?
It would be great to be able to force rebuild from the UI to get the correct size shown.

**Comment by pastelsky** [comment]
Interesting. This shouldn't happen now ideally since we use the npm registry as the source of truth for resolving package versions now.

For now, I've force-indexed the version you specified. Feel free to open a new issue if you notice this happen again.
