### ISSUE TITLE
BuildError: `@slidy/core@3.0.3` fails to `T=e?.parentElement`

### ISSUE THREAD

**Issue by Valexr** [pastelsky/bundlephobia#606]
## @slidy/core@3.0.3

Can't compile with [Optional chaining `?.`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) & [Nullish coalescing operator `??`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)

### Entire (stringified) error that I see in my browser console

```
/tmp/tmp-build/packages/build-@slidycore-skE/node_modules/@slidy/core/dist/slidy.js 1:2334 Module parse failed: Unexpected token (1:2334) File was processed with these loaders: * ./node_modules/shebang-loader/index.js * ./node_modules/string-replace-loader/index.js You may need an additional loader to handle the result of these loaders. > 
```

**Comment by Valexr** [comment]
Any progress ? 
I'm replace modern operators to older syntax in v3.0.5, but i want use it & have bandlephobia badge in repo 🤓

**Comment by fregante** [comment]
This issue is being tracked in https://github.com/pastelsky/bundlephobia/issues/530

**Comment by pastelsky** [comment]
This works now after our new update —
https://bundlephobia.com/package/@slidy/core@3.0.3

Thanks for your patience!
