### ISSUE TITLE
BuildError: type-plus fails to build this package (nullish coalescing operator)

### ISSUE THREAD

**Issue by unional** [pastelsky/bundlephobia#620]
## Package name

https://github.com/unional/type-plus

### Entire (stringified) error that I see in my browser console

```
/tmp/tmp-build/packages/build-type-plus-JuB/node_modules/type-plus/esm/object/split.js 4:95 Module parse failed: Unexpected token (4:95) File was processed with these loaders: * ./node_modules/shebang-loader/index.js * ./node_modules/string-replace-loader/index.js You may need an additional loader to handle the result of these loaders. | export function split(target, ...splitters) { | const keyMap = {}; > const s = splitters.map(s => reduceByKey(s, (p, k) => (keyMap[k] = true, p[k] = target[k] ?? s[k], p), {})); | const r = reduceByKey(target, (p, k) => keyMap[k] ? p : (p[k] = target[k], p), {}); | return [...s, r]; @ /tmp/tmp-build/packages/build-type-plus-JuB/node_modules/type-plus/esm/object/index.js 16:0-24 16:0-24 @ /tmp/tmp-build/packages/build-type-plus-JuB/node_modules/type-plus/esm/index.js @ /tmp/tmp-build/packages/build-type-plus-JuB/index.js
```

It is because bundlephobia currently does not support [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)

**Comment by Valexr** [comment]
& [Optional chaining `?.`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) too

**Comment by Valexr** [comment]
https://github.com/pastelsky/bundlephobia/issues/606

**Comment by GRA0007** [comment]
This issue is being tracked in #530

**Comment by pastelsky** [comment]
This should work now with the latest update of Bundlephobia —
https://bundlephobia.com/package/type-plus@4.10.2

Thanks for your patience.
