### ISSUE TITLE
Your website is down.

### ISSUE THREAD

**Issue by KnorpelSenf** [pastelsky/bundlephobia#637]
I am not sure if you are aware of that already, so I thought I'd just let you know that it's giving a 502 for quite some time now.

**Comment by pavinduLakshan** [comment]
I'm also experiencing this issue..

**Comment by Milkywayrules** [comment]
yup, still the same today

**Comment by geekact** [comment]
It works now.

**Comment by KnorpelSenf** [comment]
Can confirm. Thanks for bringing it back up!

Closing.
