### ISSUE TITLE
Website seems to be down

### ISSUE THREAD

**Issue by nickluger** [pastelsky/bundlephobia#656]
![Bildschirmfoto 2022-06-21 um 08 47 36](https://user-images.githubusercontent.com/32647249/174734535-b85f50c0-3702-4e6d-907f-40979271f24c.png)
![Bildschirmfoto 2022-06-21 um 08 47 01](https://user-images.githubusercontent.com/32647249/174734540-2be788bf-c72a-4136-a071-08fe13fdcca4.png)

**Comment by jonathan-emed** [comment]
Its back up but it still fails when trying mode modules like `serverless`

**Comment by pastelsky** [comment]
Closing this, as the issues causing the 5xxs have been fixed. For any new build failures, kindly raise a new issue with the right template so we can have a better discussion.
