### ISSUE TITLE
[Feature Request] size of all sub-dependencies

### ISSUE THREAD

**Issue by kubenstein** [pastelsky/bundlephobia#68]
Love the tool! I use `bundlephobia` as a one of many steps to evaluate a package and what I think may be useful is to include (maybe optionally) also total size of all dependencies recursively. Eventually sub-dependencies are the main source of `the bloat`.

**Comment by pastelsky** [comment]
Hi @kubenstein,

It's a great idea. The composition of the package can indeed be very insightful. I hacked on something similar this weekend. You might not see it on all packages yet (indexing in the process), but here's how it looks - https://bundlephobia.com/result?p=d3@5.5.0 

What do you think?

**Comment by kubenstein** [comment]
hi @pastelsky!
such an amazing work! thank you! We can see now that often a package code is just a tiny percentage of the code we load - majority comes from dependencies. Great work! Is the size of each dependency calculation also considers that dependency dependencies?

**Comment by pastelsky** [comment]
These should be the direct dependencies of the package, if I'm right.

**Comment by 8eecf0d2** [comment]
Any chance you can elaborate on the indexing process? I really like the composition breakdown but have noticed it's not always up to date.

Example: [bundlephobia.com/result?p=jagwah@0.0.14](https://bundlephobia.com/result?p=jagwah@0.0.14) still shows `url-pattern` in the composition although it has been removed in `jagwah@0.0.14`

Thanks again for your work on bundlephobia!

**Comment by pastelsky** [comment]
@8eecf0d2 yikes. That doesn't look alright. Will check why that's happening. Package upgrades have been one of those areas that haven't been tested a whole bunch.

**Comment by 8eecf0d2** [comment]
Could this actually be a caching issue? Doesn't make much sense but sort of feels right.
I assume if I target `package@x.x.x` and the cache can't find it, the build attempt will fail but if I was to target `package@latest` then it could run into some weird situations - especially if multiple / different caches are used.

**Comment by pastelsky** [comment]
This is fixed. Further discussion on this at #73
