### ISSUE TITLE
Doesn't work for the 'victory' package

### ISSUE THREAD

**Issue by sasneutrino** [pastelsky/bundlephobia#69]
MissingDependencyError
This package (or this version) uses `prop-types` and `react`, but does not specify them either as a dependency or a peer dependency.

**Comment by pastelsky** [comment]
The error is self documenting.  See https://github.com/pastelsky/bundlephobia#1-why-does-search-for-package-x-throw-missingdependencyerror-

**Comment by pastelsky** [comment]
Closing this, since it needs to be solved at the package level.

**Comment by ryan-roemer** [comment]
As someone who's wrangled a lot of packages with different use cases over the years, `peerDependencies` are not always present nor needed in modern npm development.

However, for testing, nearly always a package will include all dependencies somewhere. It may be worth a consideration of installing `devDependencies` (or even as a heuristic for something more efficient, do a two pass build. If first pass fails for deps, grep and install them if present from `devDependencies`).

**Comment by pastelsky** [comment]
@ryan-roemer Doing a two pass build would more than double the time it currently takes to build packages – for reference – large packages over 1 MB take close to 30s to build. Also, `devDependencies` are usually much heavier than dependencies, so installing them all would increase build times many times over, which does not look like a practical solution.

It's wholly possible that the `peerDependency` isn't specified as a `devDependency` at all, in which case, the two pass system fails as well. Without a reference to which version of the dependency the project depends on, it's isn't possible to calculate accurate sizes.

So while `peerDependencies` are not a strict requirement, they currently offer the only possible way for a static build tool to figure map project dependencies. And a majority of npm packages continue to use the field / are open to adding it.

**Comment by pastelsky** [comment]
This is solved now.  For eg. see -
https://bundlephobia.com/result?p=victory@31.0.2

Thanks everyone for pitching in. I was skeptical about it initially, but then there were too many packages that didn't bother adding `peerDepenencies`, and it reduced bundlephobia's helpfulness as a tool. It's a lot more forgiving about such dependencies now, but with clear warnings.
