### ISSUE TITLE
UI is one version late

### ISSUE THREAD

**Issue by thomasthiebaud** [pastelsky/bundlephobia#70]
## Type
Bug

## Package name
htmldom-to-react

### Entire error (stringified) I see in my browser console
It seems that the UI is one version late. If I go to https://bundlephobia.com/result?p=htmldom-to-react@1.8.0, I see

<img width="1427" alt="screen shot 2018-07-09 at 20 44 36" src="https://user-images.githubusercontent.com/3715715/42469765-f12aede8-83b8-11e8-9b1f-825d85871d10.png">

which correspond to version `1.7.0` (https://github.com/thomasthiebaud/htmldom-to-react/tree/v1.7.0).

version 1.8.0 as no dependency on `deepmerge` anymore (https://github.com/thomasthiebaud/htmldom-to-react/tree/v1.8.0)

**Comment by pastelsky** [comment]
Well, that's strange. I tried looking to see if this had happened with other packages as well (all packages were re-indexed recently), and from what I could see, only `htmldom-to-react` has this issue. 

Will randomly inspect to see if theirs a bigger problem here. In case you find any other package displaying this behaviour, do let me know.

**Comment by thomasthiebaud** [comment]
I change the name of my package (https://bundlephobia.com/result?p=htmlstring-to-react@2.0.0) and I cannot reproduce the bug. I will close this issue for now.
