### ISSUE TITLE
[Just a question] Integrating the API in https://bestofjs.org/

### ISSUE THREAD

**Issue by michaelrambeau** [pastelsky/bundlephobia#72]
Hello @pastelsky ,
First thank you for your amazing work, _Bundlephobia_ is a great tool to check bundle sizes!

I run an open-source application called "Best of JavaScript" https://bestofjs.org/ that gathers trends and data about a curated list of about 1300 projects related to the web platform.

![image](https://user-images.githubusercontent.com/5546996/43041825-bc374a44-8da6-11e8-8e2b-20d4ae2d2f8e.png)

I'd like to include data from _Bundlephobia_ in _Best of JavaScript_ so that users can check and compare easily the bundle sizes.
As mentioned in this issue https://github.com/bestofjs/bestofjs-webui/issues/61, I plan to use the following API end-point:

https://bundlephobia.com/api/size?package=redux

I just wanted to be sure you're OK with this idea, of course I'd mention that data comes from bundlephobia.com.

And I'd avoid to put too much pressure on your server 😄 , only requesting data for packages that have been updated on NPM, once a day.

Thank you for your feedback!

**Comment by pastelsky** [comment]
Thanks for writing in. You need to be aware of a couple of things - 

1) There is rate limiting for requests, so you may need to throttle them.
2) Please add a custom user agent to the request, so it's easy to track down the source of the request easily, and accordingly, assign it a QoS tier.

Also, as an estimate, how many requests do you think you would you be making in a day?

**Comment by michaelrambeau** [comment]
Hello Shubham @pastelsky ,
Thank you very much for your answer.

I noticed the rate limit ("Too many requests") when I tried to initialize data for all the existing projects, on Sunday, I had to make one request at a time but it worked.

Every day, I'd like to make API calls for 2 kinds of projects:

* the new projects that were added to _Best of JavaScript_: about 1 project every day
* the existing projects that were updated in NPM (the projects whose version number changed since the last run): about **20** packages a day (I found 40 packages updated in 48 hours, among the existing projects)

To be safe, we could say: **up to 50 requests a day**.

I've just done some tests, using `QoS tier` as a User-Agent.

I can setup something more explicit: `QoS tier Best of JavaScript approved by Shubham issue #72`, what do you think? So that nobody will ever consider these requests as coming from spammers, in the future... I'm not a robot! 🤖 😄 

Thank you again!

**Comment by pastelsky** [comment]
Yeah, that sounds reasonable. Also, in the future we might have a way to get past the blanket rate-limiting that currently applies for all API requests, so you don't have to worry about queueing up the requests yourself.

About the UserAgent - Just adding "bestofjs" or "bestofjs.com" to the UA should suffice. 

We might offer API keys in the future to avoid both the issues, but yeah, #lazydev for now.

Go ahead and build awesome stuff. Goodluck!

**Comment by michaelrambeau** [comment]
Thank you @pastelsky 

OK, no problem at all, the User-Agent will be set to: `QoS tier bestofjs.com`

I will show you something as soon as a demo is ready.

**Comment by pastelsky** [comment]
I'm sorry, but can I request a change? Instead of setting a user agent, could you add a custom header 
`x-bundlephobia-user`: `bestofjs.com` ? Might be easier for you as well.

**Comment by michaelrambeau** [comment]
@pastelsky No problem at all, I'm doing that, thank you.

I'm doing some tests right now, using the custom header.

**Comment by michaelrambeau** [comment]
@pastelsky Hello again, your server may have seen some requests from `bestofjs.com`.

During the test I noticed that `saber` package ("A minimalistic framework for building static website using Vue.js") generates an `Internal Server Error` (no JSON returned by the server).

It may be a timeout somewhere because it took almost 20 seconds to get the error.

https://bundlephobia.com/api/size?package=saber

**Comment by michaelrambeau** [comment]
Hello @pastelsky !

We worked on _Bundle Phobia_ integration. Bundle data could be displayed this way:

![image](https://user-images.githubusercontent.com/5546996/44007569-2a2d147e-9ed3-11e8-9ed5-bec58dd61923.png)

Would it be OK for you?

Any update about the errors I mentioned above? (We still get an error for `saber` package)

Thank you for your feedback!

**Comment by michaelrambeau** [comment]
Hello Shubham @pastelsky 

Just to confirm, the latest release of https://bestofjs.org/ integrates _Bundle Phobia_ data, as you can see here.

![image](https://user-images.githubusercontent.com/5546996/44366288-2a6de780-a507-11e8-80f5-0cd4ab21f454.png)

Thank you for your support!
