### ISSUE TITLE
last changes broke the UI

### ISSUE THREAD

**Issue by steve-py96** [pastelsky/bundlephobia#734]
**Describe the bug**

A picture says more than thousand words:
<img width="1236" alt="screenshot" src="https://user-images.githubusercontent.com/10261694/209351574-a530c9ed-1850-4a52-a245-fcc1cd9843f4.png">

**To Reproduce**

Search for any package with many versions, f.e. https://bundlephobia.com/package/jotai@1.12.0

**Expected behavior**

As before, only x versions shown

---

**Additional stuff**
bundlephobia is greatness, happy xmas days! 🎄

**Comment by qw-in** [comment]
You beat me to it! 

<img width="1496" alt="Bundlephobia website where bar chart is covering the important details" src="https://user-images.githubusercontent.com/19194187/209451542-2682cf72-95a2-4a2e-b29d-9a7c7776445c.png">


(apple m1, firefox)

**Comment by steve-py96** [comment]
fixed with https://github.com/pastelsky/bundlephobia/commit/a71226539c3cc743ada101a9c3ab799c7ce32efd 👍🏿
