### ISSUE TITLE
Next.js package `next` is blacklisted

### ISSUE THREAD

**Issue by Haltarys** [pastelsky/bundlephobia#749]
**Describe the bug**

The package [`next`](https://www.npmjs.com/package/next) errors with "*BlacklistedPackageError* The package you were looking for is blacklisted because it failed to build multiple times in the past and further tries aren't likely to succeed. This can happen if this package wasn't meant to be bundled in a client side application."

**To Reproduce**

Search to compute size for `next`, or directly go to <https://bundlephobia.com/package/next>.

**Expected behavior**

I doubt a package from Vercel with over 3 million weekly downloads fails to build. Does it count as "not client-side" ? I think I should be able to see it, unless it was blacklisted for another reason.

**Comment by ekwoka** [comment]
It fails to build because it can't be built for browsers which is what bundlephobia is for.

**Comment by styfle** [comment]
I think you'll want to try out https://packagephobia.com instead 😃

**Comment by pastelsky** [comment]
Yeah, bundlephobia isn't meant to handle server-side packages (though it does work for most of them). Next is quite heavy to compile and ship, and it cannot be built by webpack. 

Packagephobia is better option for these :)
