### ISSUE TITLE
"main" without file extension isn't working correctly

### ISSUE THREAD

**Issue by abraham** [pastelsky/bundlephobia#75]
## Type
node-fetch 2 updated `package.json` to have `"main": "lib/index"` and the size is now wrong. Which seems to be [valid](https://stackoverflow.com/a/46900211/26406).

## Package name
[`node-fetch`](https://bundlephobia.com/result?p=node-fetch@2.2.0)

### Entire error (stringified) I see in my browser console
n/a

**Comment by abraham** [comment]
You're right, thanks. I was reading it wrong.

**Comment by wopian** [comment]
[Packagephobia](https://packagephobia.now.sh/result?p=node-fetch) would be better suited for node-only packages like this.
