### ISSUE TITLE
https://bundlephobia.com/ is down

### ISSUE THREAD

**Issue by azu** [pastelsky/bundlephobia#755]
**Describe the bug**

https://bundlephobia.com/ origin server is down.

<img width="2386" alt="image" src="https://user-images.githubusercontent.com/19714/221101394-16810c3d-e428-4a73-8c0a-bbc0ad8eeca5.png">

Current show snapshot page by cloudflare

> This website bundlephobia.com/ is currently offline. Cloudflare's Always Online™ shows a snapshot of this web page from the Internet Archive's Wayback Machine. To check for the live version, click Refresh.

**To Reproduce**

1. Visit https://bundlephobia.com/
2. Input "lodash"
3. Response is "InternalServerError"

**Expected behavior**

Show lodash bundle result

**Comment by pastelsky** [comment]
Should be back up  
I was on a break — so didn't notice this, and looks like `pm2` bailed out on me.

Thanks for reporting this, and sorry for the inconvenience meanwhile ❤️

**Comment by azu** [comment]
Thanks!

**Comment by micahjon** [comment]
Just an FYI that it's down again
https://bundlephobia.com/package/devalue

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/9473554/227757605-fd070da1-d721-4d7c-8384-e0d5d958ec26.png">
