### ISSUE TITLE
InternalServerError on package "mdn-browser-compat-data"

### ISSUE THREAD

**Issue by jaylinski** [pastelsky/bundlephobia#77]
## Type

Bug

## Package name

mdn-browser-compat-data

### Entire error (stringified) I see in my browser console

`GET https://bundlephobia.com/api/size?package=mdn-browser-compat-data&record=true 504`
`SyntaxError: Unexpected token < in JSON at position 0`

The error is shown because cloudflare returns a gateway-timeout page:
`Error 504 Ray ID: 4482e7a74b8459ba • 2018-08-10 13:46:47 UTC`

(This project is awesome by the way! :heart:)

**Comment by wopian** [comment]
Also happens for:

- @babel/runtime v7.0.0-rc.1
- kitsu-core v6.0.1
- kitsu v6.0.0

**Comment by pastelsky** [comment]
Thanks for reporting! It should be fixed now.
