### ISSUE TITLE
BuildError: xml-template-literal fails to build.

### ISSUE THREAD

**Issue by Olian04** [pastelsky/bundlephobia#773]
## Package name

```
xml-template-literal
```

### Entire (stringified) error that I see in my browser console

```
Export analysis failed due to  {
    "error": {
        "code": "BuildError",
        "message": "Failed to build this package.",
        "details": {
            "name": "BuildError"
        }
    }
} error: code: "BuildError"details: name: "BuildError"[[Prototype]]: Objectmessage: "Failed to build this package."[[Prototype]]: Object[[Prototype]]: Object
overrideMethod @ react_devtools_backend.js:2655
(anonymous) @ [...packageString]-8dec680ff2abc7e3.js:1
Promise.catch (async)
(anonymous) @ [...packageString]-8dec680ff2abc7e3.js:1
componentDidMount @ [...packageString]-8dec680ff2abc7e3.js:1
uX @ framework-3b5a00d5d7e8d93b.js:9
e @ framework-3b5a00d5d7e8d93b.js:9
(anonymous) @ framework-3b5a00d5d7e8d93b.js:9
oU @ framework-3b5a00d5d7e8d93b.js:9
ox @ framework-3b5a00d5d7e8d93b.js:9
x @ framework-3b5a00d5d7e8d93b.js:33
T @ framework-3b5a00d5d7e8d93b.js:33
```

<img width="797" alt="Screenshot 2023-04-12 at 15 52 46" src="https://user-images.githubusercontent.com/5493406/231480591-182b5ef6-2027-43c8-b187-fc7ac83053a9.png">

**Comment by upteran** [comment]
Hi, did investigate of this error and figure out it generates in webpack's `enhanced-resolve`  module, with message below
```
 Package path . is not exported from package /tmp/tmp-build/packages/build-xml-template-literal-eih/node_modules/xml-template-literal (see exports field in /tmp/tmp-build/packages/build-xml-template-literal-eih/node_modules/xml-template-literal/package.json)
```

Probably problem in `export` field in `xml-template-literal` package.json file. Here found some good describe of example with this [problem](https://github.com/ai/nanoid/issues/234#issuecomment-798959918) 
In my opinion, have two options to resolve:
- add `conditionNames` param to `package-build-stats` pack  (where placed `enhanced-resolve`)
- add to xml-template-literal `default` field inside exports field, for ex: 
```
  "exports": {
    "import": "./dist/api.js",
    "require": "./legacy/umd.cjs",
    "types": "./dist/api.d.ts",
    "default": "./legacy/umd.cjs"
  },
```

Think second option faster, but mb it's some common case and need to improve `package-build-stats` config, but with this point maybe @pastelsky will help, because I may not know some details

**Comment by cefn** [comment]
How did you get visibility of the underlying error? I'm facing an anonymous `BuildError Failed to build this package.` https://bundlephobia.com/package/@watchable/store@0.9.0-alpha.2 which I'm happy to pursue further but not sure how I can see it failing on my machine as you did. Maybe i need `"types"` and `"default"` when I currently have just ["import" and "require"](https://github.com/cefn/watchable/blob/main/packages/store/package.json#L18-L19) but without being able to run the build procedure it's hard to tell.

**Comment by upteran** [comment]
@cefn I've run project and checked error middleware. I see the same error with your package `Package path . is not exported from...`
You can check how it resolved with `enhanced-resolve` separately from bundlephobia, using only this module, [for example](https://github.com/upteran/enhanced-resolve-module-test), and test directly your module

**Comment by Olian04** [comment]
> Hi, did investigate of this error and figure out it generates in webpack's `enhanced-resolve` module, with message below
> 
> ```
>  Package path . is not exported from package /tmp/tmp-build/packages/build-xml-template-literal-eih/node_modules/xml-template-literal (see exports field in /tmp/tmp-build/packages/build-xml-template-literal-eih/node_modules/xml-template-literal/package.json)
> ```
> 
> Probably problem in `export` field in `xml-template-literal` package.json file. Here found some good describe of example with this [problem](https://github.com/ai/nanoid/issues/234#issuecomment-798959918) In my opinion, have two options to resolve:
> 
> * add `conditionNames` param to `package-build-stats` pack  (where placed `enhanced-resolve`)
> * add to xml-template-literal `default` field inside exports field, for ex:
> 
> ```
>   "exports": {
>     "import": "./dist/api.js",
>     "require": "./legacy/umd.cjs",
>     "types": "./dist/api.d.ts",
>     "default": "./dist/api.js"
>   },
> ```
> 
> Think second option faster, but mb it's some common case and need to improve `package-build-stats` config, but with this point maybe @pastelsky will help, because I may not know some details

Thank you. This seems to have resolved the build error. However the "Exports Analysis" remains empty. It just says "GZIP sizes of individual exports".
<img width="600" alt="Screenshot 2023-05-02 at 18 03 11" src="https://user-images.githubusercontent.com/5493406/235721780-db67b5be-e008-4ecc-ace8-879ebe4920a8.png">

**Comment by cefn** [comment]
> @cefn I've run project and checked error middleware. 

Thanks for your clear description of how to recreate the resolution issue we are experiencing! Fixed in https://bundlephobia.com/package/@watchable/store@0.9.0-alpha.3

**Comment by Olian04** [comment]
@upteran that resolves it. Thank you.
