### ISSUE TITLE
redux-first-router fails to get parsed and report the size.

### ISSUE THREAD

**Issue by aga5tya** [pastelsky/bundlephobia#8]
@pastelsky, The tool is unable to parse the redux-first-router package. It does consist of the entry point and valid dist. Any pointers as to what is going wrong here?

cc /@faceyspacey

**Comment by pastelsky** [comment]
It works with the new release -
https://bundlephobia.com/result?p=redux-first-router@0.0.16-next

**Comment by faceyspacey** [comment]
20 is in fact the latest. Just make sure ur using 20. There might have been one mini release that had a problem. Check ur node modules for the exact version. Sometimes they don't give u the true latest I noticed with npm vs yarn
