### ISSUE TITLE
Missing history

### ISSUE THREAD

**Issue by oliviertassinari** [pastelsky/bundlephobia#81]
## Type

Navigating to https://bundlephobia.com/result?p=@material-ui/core@1.5.1, we can only see the current version.
![capture d ecran 2018-08-20 a 09 45 39](https://user-images.githubusercontent.com/3165635/44327023-c80cdc80-a45d-11e8-84d7-fc0e9cb66a77.png)

We have been doing a lot of effort for reducing the bundle size over the last few months. I wish we could see more versions of this package, so we could celebrate the success.

## Package name

[`@material-ui/core`](https://github.com/mui-org/material-ui)

**Comment by pastelsky** [comment]
I think it was only recently that `material-ui` moved to using scoped package names. Bundlephobia filter out beta/release versions (except the most recent beta). 

Hence the history might be missing.

**Comment by oliviertassinari** [comment]
@pastelsky But what about?
![capture d ecran 2018-08-21 a 17 46 08](https://user-images.githubusercontent.com/3165635/44412832-232bf580-a56a-11e8-9e9f-0a5b8ddab319.png)

**Comment by pastelsky** [comment]
Closing this, since this seems to be fixed after the `v2` release.

**Comment by oliviertassinari** [comment]
It was :)
