### ISSUE TITLE
[feature request] open search description

### ISSUE THREAD

**Issue by leoweigand** [pastelsky/bundlephobia#86]
## Feature request: Open Search Description
It would be great to search packages directly from the search bar as seen in this example from stackoverflow:

<img width="199" alt="screen shot 2018-09-01 at 00 45 45" src="https://user-images.githubusercontent.com/5489276/44938647-7bd86b00-ad80-11e8-8df7-9eb02547562d.png">

This is also easy to implement, see https://developer.mozilla.org/en-US/docs/Web/OpenSearch for more information.

Absolutely loving the site btw 👍

**Comment by pastelsky** [comment]
Would you like to send a PR? You can find the public files here - https://github.com/pastelsky/bundlephobia/tree/bundlephobia/assets/public

**Comment by leoweigand** [comment]
Is there anything missing in the PR? Would be great to have this feature :)
