### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by rubengmurray** [pastelsky/bundlephobia#890]
**Describe the bug**

Didn't know a better place to put this....

- When I go to [bundlephobia](https://bundlephobia.com/) I get a CloudFlare / WaybackMachine image, followed by a Bad Gateway on search

<img width="1725" alt="Screenshot 2024-08-29 at 16 55 13" src="https://github.com/user-attachments/assets/c178e75b-d983-4104-935c-a927cfe5af3a">

<img width="1695" alt="Screenshot 2024-08-29 at 16 55 26" src="https://github.com/user-attachments/assets/9aacbad1-68b1-4a94-8e28-feba76d8a957">

**To Reproduce**

- [bundlephobia](https://bundlephobia.com/)

**Expected behavior**

**Comment by ilyaskarim** [comment]
Same here!

**Comment by rubengmurray** [comment]
Still an issue for me. Is this still maintained? 

Seems to have a fair amount of support on OpenCollective: https://opencollective.com/bundlephobia

**Comment by SalahAdDin** [comment]
Still down!

**Comment by rubengmurray** [comment]
Looks like it's back?

**Comment by rubengmurray** [comment]
Working consistently for a few days now. I'll close this issue.
