### ISSUE TITLE
Update firebase to the latest version 4.2.0

### ISSUE THREAD

**Issue by palashmon** [pastelsky/bundlephobia#9]
There is a newer version of [**firebase**](https://www.npmjs.com/package/firebase) released that this project depends on.

Dependency | firebase
:-- | :--
**Required** | ^3.7.3
**Latest** | 4.2.0

There might be a bunch of new features, fixes and perf improvements that might help this project.
Please have a look into these changes and try to get onto the latest version of **firebase**.

Regards!

**Comment by pastelsky** [comment]
We're on v4.x in the latest beta. Thanks for reporting.
