### ISSUE TITLE
Improvements to the scan package blacklist

### ISSUE THREAD

**Issue by edmorley** [pastelsky/bundlephobia#90]
## Type
Somewhere between a bug and a feature request :-)

## Package name
N/A

## Summary
Hi - thank you for a great tool!

The scan feature (https://bundlephobia.com/scan) uses a set of regexes to determine which packages should be unchecked by default:
https://github.com/pastelsky/bundlephobia/blob/bundlephobia/pages/scan/scanBlacklist.js

After uploading this `package.json`:
https://github.com/mozilla/treeherder/blob/master/package.json

...there were the following items checked that would ideally match the blacklist but didn't:
- `@types/angular`
- `@types/prop-types`
- `@types/react`
- `@types/react-dom`
- `eslint`
- `eslint-config-airbnb`
- `eslint-plugin-import`
- `eslint-plugin-jsx-a11y`
- `eslint-plugin-react`

This seems best fixed by adding the regexes `/eslint/` and `/@types\//` ?

...and the following were unchecked when they shouldn't be (ie blacklist false positives):
- `angular-clipboard` (caught by `/cli/`)
- `prop-types` (explicitly listed)
- `react-hot-loader` (explicitly listed)
- `taskcluster-client-web` (caught by `/cli/`)

The two react entries should not be blacklisted, since it's typical for projects to import them directly in their entrypoints even in production (unless they happen to be using `babel-plugin-transform-react-remove-prop-types` in the case of `prop-types`). See:
https://github.com/gaearon/react-hot-loader#getting-started
https://www.npmjs.com/package/prop-types#how-to-depend-on-this-package

That said, they actually ship a reduced bundle when `NODE_ENV === 'production'`, so the impact is minimal:
https://unpkg.com/react-hot-loader@4.3.6/index.js
https://unpkg.com/prop-types@15.6.2/index.js

For the other two, changing the `/cli/` regex to use word-boundaries seems like it might be the best fix?

I'll try to open a PR when I get a moment, though if anyone else would like to in the meantime, go ahead :-)

**Comment by pastelsky** [comment]
PRs to improve this welcome!
