### ISSUE TITLE
Website Down: Unable to Access bundlephobia.com

### ISSUE THREAD

**Issue by AntoineKM** [pastelsky/bundlephobia#904]
**Describe the bug**
Hey @pastelsky, it seems the website is currently down.

<img width="1481" alt="image" src="https://github.com/user-attachments/assets/919c41e7-f309-45bf-b806-bf47344fdb6e">

**To Reproduce**
1. Open your browser.
2. Navigate to https://bundlephobia.com/.
3. Observe the website being inaccessible.

**Expected behavior**
The website should load and be accessible without issues.

**Comment by elijaholmos** [comment]
I'm getting the same error

**Comment by joeyfigaro** [comment]
@pastelsky 🔔 

anything we can help with here?

**Comment by AntoineKM** [comment]
Seems to be solved !
