### ISSUE TITLE
[feature request] Badges service

### ISSUE THREAD

**Issue by jakub-g** [pastelsky/bundlephobia#91]
## Type
Feature Request

## Details

The badge of honor (pun intended) of any self-respecting GitHub repo is to display a few fancy badges like below:

![image](https://user-images.githubusercontent.com/1437027/45417324-2bb3af80-b682-11e8-977a-88ff9ade95f7.png)

What would be really cool is to have the bundlephobia badges with the sizes of `latest` version (to be decided: min? gzip? min+gzip? IMO min is the most relevant).

This could probably be a separate project in itself. (or maybe there's already something like this that I overlooked?)

**Comment by wopian** [comment]
https://badgen.net/#bundlephobia
https://flat.badgen.net/#bundlephobia

**Comment by jakub-g** [comment]
Also:
https://shields.io/#/examples/size

This is a dupe of #4 BTW

I think badge info should be added to `README.md`
