### ISSUE TITLE
react-hotkeys build fails with "Import statement may only appear at top level"

### ISSUE THREAD

**Issue by edmorley** [pastelsky/bundlephobia#93]
## Type
Bug

## Package name
https://www.npmjs.com/package/react-hotkeys
https://bundlephobia.com/result?p=react-hotkeys

### Entire error (stringified) I see in my browser console
```json
{
  "error": {
    "code": "BuildError",
    "message": "Failed to build this package.",
    "details": {
      "name": "BuildError",
      "originalError": [
        "minifying bundle.js\nImport statement may only appear at top level"
      ]
    }
  }
}
```

**Comment by jakub-g** [comment]
For the record, we have the same issue with `vast-client` https://bundlephobia.com/result?p=vast-client https://github.com/dailymotion/vast-client-js/issues/249#issuecomment-442508158

**Comment by pastelsky** [comment]
The error is self-descriptive here.
