### ISSUE TITLE
[bug] node restarts?

### ISSUE THREAD

**Issue by budnix** [pastelsky/bundlephobia#95]
## Type

It seems that one of the packages which are close to my interest generate an error which causes node restart?

## Package name
[@handsontable/react](https://bundlephobia.com/result?p=@handsontable/react) 
[@handsontable/angular](https://bundlephobia.com/result?p=@handsontable/angular) 

### Entire error (stringified) I see in my browser console
`{"error":{"code":"MissingDependencyError","message":"This package (or this version) uses `<code>react</code>`, but does not specify them either as a dependency or a peer dependency","details":{"name":"MissingDependencyError","originalError":["ModuleNotFoundError: Module not found: Error: Can't resolve 'react' in '/tmp/tmp-build/packages/build-@handsontablereact@1.1.0/node_modules/@handsontable/react/dist'"],"extra":{"missingModules":["react"]}}}}`

**Comment by pastelsky** [comment]
Don't see this happening now. Closing this. Thanks for reporting.
