### ISSUE TITLE
Can we have size badge

### ISSUE THREAD

**Issue by MurhafSousli** [pastelsky/bundlephobia#99]
## Type

Feature Request

It would be really if we can have a size badge that we can add in the README page, something like:

[![npm](https://img.shields.io/badge/Size-3.2kb-brightgreen.svg)](https://murhafsousli.github.io/ngx-progressbar/)

**Comment by fabienjuif** [comment]
Hi @MurhafSousli you have some pointers here: https://github.com/pastelsky/bundlephobia/issues/91

-> It already exists from tiers apps 👍

**Comment by styfle** [comment]
Also here https://badgen.net/#bundlephobia

**Comment by MurhafSousli** [comment]
@fabienjuif Got it 😄 thanks!
